Normation/rudder-doc

12_upgrade/20_upgrade_centos_rhel.txt, 12_upgrade/30_upgrade_suse.txt
http://www.rudder-project.org/redmine/issues/6503
=> Fixes #6503: Update command on centos is missing \"ncf-api-virtualenv\" package

glossary/big-red-button.txt, glossary/cf-serverd.txt
http://www.rudder-project.org/redmine/issues/6596
=> Fixes #6596: Remove references to the Big Red Button in the manual

5_references/50_generic_methods.txt, Makefile, README.asciidoc, tools/ncf_doc_rudder.py, xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/7844
=> Fixes #7844: Integrate ncf generic methods reference into the doc

4_advanced_usage/40_node_properties.txt
https://www.rudder-project.org/redmine/issues/8755
=> Fixes #8755: Document node properties

4_advanced_usage/75_separate_database.txt
https://www.rudder-project.org/redmine/issues/8908
=> Fixes #8908: Document separate database configuration in Rudder

4_advanced_usage/50_script_in_directives.txt
https://www.rudder-project.org/redmine/issues/8804
=> Fixes #8804: Give more precise requirements for JVM to manage AIX sha256/512 passwords

8_reference/71_reports.txt
https://www.rudder-project.org/redmine/issues/9588
=> Fixes #9588: Document new audit reports type in techniques reference

Makefile
https://www.rudder-project.org/redmine/issues/9621
=> Fixes #9621: Manual is broken because of some new syntax in ncf doc

Makefile
https://www.rudder-project.org/redmine/issues/9803
=> Fixes #9803: We should disable link tests for the manual on master 

8_reference/80_relay_api.txt
https://www.rudder-project.org/redmine/issues/10152
=> Fixes #10152: Missing async option in the doc

Makefile
https://www.rudder-project.org/redmine/issues/10206
=> Fixes #10206: Merge error - Link check disappeared in 4.0

8_reference/73_techniques_best_practices.txt
https://www.rudder-project.org/redmine/issues/10222
=> Fixes #10222: Add guideline for technique naming

8_reference/74_package_format.txt
https://www.rudder-project.org/redmine/issues/10255
=> Fixes #10255: Document plugin package format

4_advanced_usage/18_build_agent.txt
https://www.rudder-project.org/redmine/issues/10333
=> Fixes #10333: Document how to build a and agent

10_installation/10_install_server/11_install_root_server_debian.txt, 10_installation/10_install_server/12_install_root_server_sles.txt, 12_upgrade/10_upgrade_debian.txt, 12_upgrade/30_upgrade_suse.txt
https://www.rudder-project.org/redmine/issues/10548
=> Fixes #10548: Rudder documentation and release note don't mention the dependency to Java 1.8 for Rudder 4.1

00_introduction/20_key_features.txt, 80_extension_and_integration/20_Rudder_plugins.txt, 80_extension_and_integration/40_Rudder_Integration.txt
https://www.rudder-project.org/redmine/issues/10687
=> Fixes #10687: Broken doc build

43_advanced_administration/20_application_tuning.txt
https://www.rudder-project.org/redmine/issues/8613
=> Fixes #8613: Missing documentation about InputTCPMaxSessions and when to change its value in rsyslog

10_installation/11_install_agent/80_agent_configuration.txt
https://www.rudder-project.org/redmine/issues/12569
=> Fixes #12569: Wrong service name in agent install instruction in 4.3

10_installation/05_requirements/10_jvm_requirements.txt
https://www.rudder-project.org/redmine/issues/12606
=> Fixes #12606: Restricted java security policy breaks Rudder (class configured for Cipher(provider: BC)cannot be found)

90_reference/55_generic_methods_best_practices.txt
https://www.rudder-project.org/redmine/issues/12594
=> Fixes #12594: Add a doc about generic method naming conventions

src/reference/Makefile, src/reference/dependencies/.gitignore, src/reference/dependencies/Makefile, src/reference/modules/plugins/pages/index.adoc
https://issues.rudder.io/issues/14099
=> Fixes #14099: Add documentation about rudder <-> plugin version compatibility in docs

src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/14415
=> Fixes #14415: After upgrading from 4.1.7 to 5.0.8, rudder-agent is not upgraded

src/reference/modules/reference/pages/techniques.adoc
https://issues.rudder.io/issues/13619
=> Fixes #13619: Document that resource file of Techniques are shared to nodes with UTF-8 Encoding *only* (breaks for other encoding)

src/reference/modules/administration/pages/performance.adoc, src/reference/modules/administration/pages/server.adoc, src/reference/modules/administration/pages/users.adoc
https://issues.rudder.io/issues/15968
=> Fixes #15968: Use systemctl for rudder services management in docs

src/reference/modules/reference/pages/variables.adoc
https://issues.rudder.io/issues/15596
=> Fixes #15596: Document inventory variables

src/reference/modules/installation/pages/_partials/debian_repo.adoc
https://issues.rudder.io/issues/14632
=> Fixes #14632: Debian/Ubuntu install doc fails if lsb_release is not installed

src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/16224
=> Fixes #16224: Missing documentation on openssl incompatibilities between 4.x and 5.0

src/reference/modules/administration/pages/performance.adoc
https://issues.rudder.io/issues/15116
=> Fixes #15116: Document use G1GC to better deal with high volume of nodes and reports

src/reference/modules/administration/pages/relayd.adoc
https://issues.rudder.io/issues/16217
=> Fixes #16217: relayd admin guide

src/reference/modules/installation/pages/_partials/sles_repo.adoc
https://issues.rudder.io/issues/16469
=> Fixes #16469: Install doc mention Sles11 Rudder Server in 6.0 which is not supported

src/reference/modules/reference/pages/security.adoc
https://issues.rudder.io/issues/16572
=> Fixes #16572: Update security doc after 6.0

src/reference/Makefile
https://issues.rudder.io/issues/16808
=> Fixes #16808: Plugins menu in the documentation should be in alphabetical order

Makefile, rudder-theme/src/partials/navigation-explore.hbs, site-dev.yml, site.yml
https://issues.rudder.io/issues/17207
=> Fixes #17207: Fix 6.1 doc build

Makefile, src/changelogs/dependencies/Makefile
https://issues.rudder.io/issues/17212
=> Fixes #17212: Fix doc build

src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/17316
=> Fixes #17316: Document that Rudder servers should not be exposed on the Internet

src/reference/modules/installation/pages/_partials/debian_repo.adoc, src/reference/modules/installation/pages/_partials/sles_repo.adoc
https://issues.rudder.io/issues/17484
=> Fixes #17484: wrong url to download.rudder.io on 6.1

src/get-started/modules/ROOT/pages/configuration-policies/apply.adoc, src/get-started/modules/ROOT/pages/configuration-policies/directive.adoc, src/get-started/modules/ROOT/pages/configuration-policies/policy-mode.adoc, src/get-started/modules/ROOT/pages/configuration-policies/technique.adoc
https://issues.rudder.io/issues/17771
=> Fixes #17771: Add link to further information in get started section

src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/17837
=> Fixes #17837: Missing doc about root-relay communication flows

6.2.yml, Makefile
https://issues.rudder.io/issues/17962
=> Fixes #17962: Build 6.2 embedded doc

src/reference/modules/installation/pages/_partials/rhel_repo.adoc, src/reference/modules/installation/pages/_partials/sles_repo.adoc
https://issues.rudder.io/issues/18055
=> Fixes #18055: http in place of https in install doc for zypper subscription repo

src/reference/modules/plugins/pages/index.adoc
https://issues.rudder.io/issues/18391
=> Fixes #18391: Add a documentation page on how to manually distribute plugin licenses

src/reference/modules/reference/pages/build.adoc
Add note about prerequisites. Otherwise, people might build packages that don't work for non-obvious reasons (for example, failing to generate an inventory due to missing Perl modules).
=> Add note about prerequisites

src/rudder-by-example/modules/ROOT/pages/files/advanced-file-templating.adoc
https://issues.rudder.io/issues/18906
=> Fixes #18906: Add advanced jinja2 template example for main IP address

src/reference/modules/administration/nav.list, src/reference/modules/administration/pages/port.adoc
https://issues.rudder.io/issues/18872
=> Fixes #18872: Add documentation for changing cf-serverd port

src/reference/modules/installation/pages/_partials/relay_initial_config.adoc
https://issues.rudder.io/issues/19761
=> Fixes #19761: Document that a "rudder agent server-keys-reset" is necessary to move a node to another policy server

src/reference/modules/usage/pages/configuration_management.adoc
https://issues.rudder.io/issues/19919
=> Fixes #19919: Document that escaping is incoherent with the rest in Technique Editor in 6.X, that it is corrected in 7.0, and that's a breaking change

src/reference/modules/usage/pages/advanced_node_management.adoc
https://issues.rudder.io/issues/21223
=> Fixes #21223: Move create node doc in rudder core

src/reference/modules/administration/pages/relayd.adoc, src/reference/modules/installation/pages/agent/windows.adoc, src/reference/modules/reference/pages/_partials/glossary/port-443-nodes.adoc, src/reference/modules/usage/pages/advanced_node_management.adoc, src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/21347
=> Fixes #21347: Rename "DSC" and "classic" agent to "Linux" et "Windows"  in documentation

src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/21835
=> Fixes #21835: Missing ubuntu 22.04 LTS supported OS for relay and server

src/reference/modules/usage/pages/advanced_node_management.adoc
https://issues.rudder.io/issues/21952
=> Fixes #21952: Documentation for FQDN overriding

src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/22046
=> Fixes #22046: Windows agent exe link in install doc does not point to the right folder

src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/22289
=> Fixes #22289: Explain in migration doc that jetty start.ini format changed in 7.2

src/reference/modules/administration/pages/security.adoc
https://issues.rudder.io/issues/21877
=> Fixes #21877: Hardening guide for Rudder

src/reference/modules/administration/pages/security.adoc
https://issues.rudder.io/issues/22405
=> Fixes #22405: Backport hardening guide to 7.2

src/reference/modules/ROOT/pages/key_features.adoc
https://issues.rudder.io/issues/22406
=> Fixes #22406: List of authentication backend is invalid in the documentation (includes Radius)

src/reference/modules/reference/pages/build.adoc
https://issues.rudder.io/issues/17868
=> Fixes #17868: Bad documentation leads to package build failing when building for armhf

src/get-started/modules/ROOT/pages/environment/index.adoc
https://issues.rudder.io/issues/21485
=> Fixes #21485: document in the getting started that virtualbox needs a list of authorized IP

src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/22313
=> Fixes #22313: Problem in Server backup and migration documentation

src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/22554
=> Fixes #22554: Typo in windows msiexec command in documentation

src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/22767
=> Fixes #22767: proxy documentation is lost in rudder 7.3 documentation

src/reference/modules/installation/nav.adoc.src, src/reference/modules/installation/pages/_partials/al2023_repo.adoc, src/reference/modules/installation/pages/agent/rhel.adoc, src/reference/modules/installation/pages/index.adoc, src/reference/modules/installation/pages/server/al.adoc, src/reference/modules/installation/pages/server/external-db.adoc
https://issues.rudder.io/issues/22778
=> Fixes #22778: Missing documentation for AmazonLinux 2023 install for the agent

src/reference/modules/installation/pages/upgrade/sles.adoc
https://issues.rudder.io/issues/22621
=> Fixes #22621: Documentation on how to upgrade Rudder to 7.2 is invalid on zypper

src/reference/modules/administration/pages/relayd.adoc
https://issues.rudder.io/issues/22891
=> Fixes #22891: documentation on how to configure rsync relay synchroinisation is missing

src/get-started/modules/ROOT/pages/home.adoc
https://issues.rudder.io/issues/23644
=> Fixes #23644: Broken links in docs homepage - 8.0

src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/23680
=> Fixes #23680: 8.0 documentation of supported rudder-server OS is outdated

src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/24229
=> Fixes #24229: Documentation on Windows installation misses the dependency on dsc plugin on the rudder server

rudder-theme/src/partials/navigation-explore.hbs, rudder-theme/src/partials/toolbar.hbs
https://issues.rudder.io/issues/24705
=> Fixes #24705: Prepare doc for 8.1 release

src/reference/modules/installation/pages/agent/windows.adoc, src/reference/modules/reference/pages/variables.adoc
https://issues.rudder.io/issues/24234
=> Fixes #24234: Add warning for properties not case sensitive on Windows

src/reference/modules/installation/pages/upgrade/postgresql.adoc
https://issues.rudder.io/issues/9752
=> Fixes #9752: Document stopping process before Postgres restore maintenance to avoid primary key constrain get corrupted

src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/25074
Introduced by https://github.com/Normation/rudder-doc/pull/1038
=> Fixes #25074: Remove supported os for Ubuntu 24.04 for server and relay in 8.0

src/reference/modules/installation/pages/agent/windows.adoc, src/reference/modules/reference/pages/variables.adoc
https://issues.rudder.io/issues/25726
I'm not able to pinpoint was exactly changed in the code as proof, but if you need more details, ask @Fdall
=> Fixes #25726: Property name case collision is not longer a thing on Windows node since 8.2

src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/25445
=> Fixes #25445: Document the 8.2 windows variable changes
