Normation/rudder-doc

- 12_upgrade/05_caution.txt
Ticket: http://www.rudder-project.org/redmine/issues/5794
To be merged in 2.11
> Fixes #5794: Correct migration procedure to 2.11

- 10_install_server/13_install_root_server_sles.txt
- 12_upgrade/30_upgrade_suse.txt
Ticket: http://www.rudder-project.org/redmine/issues/6296
To be merged in 3.0
> Fixes #6296: Add a warning about PostgreSQL version on SLES

- 23_administration/10_archives.txt
http://www.rudder-project.org/redmine/issues/6595
> Fixes #6595: Fix asciidoc list formatting

- 00_introduction/22_architecture_root_server.txt
- 00_introduction/30_architecture_network.txt
- 10_install_server/00_install_intro.txt
- 10_install_server/12_install_root_server_sles.txt
- 10_install_server/17_initial_config.txt
- 11_install_agent/00_install_agent.txt
- 12_upgrade/00_upgrade.txt
- 20_usage/20_search_units.txt
- 21_node_management/20_node_management.txt
- 21_node_management/21_accept_new_nodes.txt
- 22_configuration_management/36_compliance.txt
- 22_configuration_management/37_validation_workflow.txt
- 23_administration/10_archives.txt
- 23_administration/20_policy_server.txt
- 23_administration/60_technique_upgrade.txt
- 23_administration/80_user_management.txt
- 4_advanced_usage/10_node_management.txt
- 4_advanced_usage/30_server_policy_generation.txt
- 4_advanced_usage/70_server_rest_api.txt
- 4_advanced_usage/91_mirroring_rudder_repositories.txt
- 5_references/10_server_data_worklow.txt
- 5_references/20_nodes_workflow.txt
- 6_handbook/10_database_maintenance.txt
- 6_handbook/20_application_tuning.txt
- glossary/active-techniques.txt
- glossary/directive.txt
- glossary/technique-library.txt
- glossary/technique.txt
http://www.rudder-project.org/redmine/issues/6599
> Fixes #6599: Check spelling and grammar of the manual

- 11_install_agent/00_install_agent.txt
- 21_node_management/22_search_nodes.txt
- 21_node_management/23_groups_of_nodes.txt
- 22_configuration_management/36_compliance.txt
- 23_administration/20_policy_server.txt
- 23_administration/70_system_password_management.txt
- 23_administration/80_user_management.txt
- 4_advanced_usage/10_node_management.txt
- 4_advanced_usage/11_node_install.txt
- 4_advanced_usage/77_distributed_rudder.txt
- 4_advanced_usage/90_server_migration.txt
- 5_references/etc/rudder-users.xml
- 6_handbook/0_handbook_intro.txt
- 6_handbook/10_database_maintenance.txt
- glossary/rudder.txt
http://www.rudder-project.org/redmine/issues/6623
> Fixes #6623: Check spelling and grammar of the 2.11 manual

- bibliography.txt
http://www.rudder-project.org/redmine/issues/6609
> Fixes #6609: Bibliography links are out of date

- 00_introduction/22_architecture_root_server.txt
http://www.rudder-project.org/redmine/issues/6607
> Fixes #6607: Broken links in the manual

- 10_install_server/12_install_root_server_rhel.txt
- 11_install_agent/10_install_agent_debian.txt
- 11_install_agent/20_install_agent_rhel.txt
- 12_upgrade/10_upgrade_debian.txt
- 12_upgrade/30_upgrade_suse.txt
- rudder-doc.txt
http://www.rudder-project.org/redmine/issues/6647
> Fixes #6647: Prepare doc for 3.1 branch

- 00_introduction/21_architecture_root_server.txt
- 11_install_agent/80_agent_configuration.txt
- 23_administration/50_services_administration.txt
- 6_handbook/15_migration_backup_restore.txt
- getting-started/getting-started.txt
http://www.rudder-project.org/redmine/issues/6645
> Fixes #6645: Update the 3.1 manual to use the new \"rudder\" init script

- 00_introduction/11_asset_management.txt
- 00_introduction/21_architecture_root_server.txt
- 10_install_server/00_install_intro.txt
- 10_install_server/12_install_root_server_rhel.txt
- 21_node_management/23_groups_of_nodes.txt
- 22_configuration_management/36_compliance.txt
- 22_configuration_management/37_validation_workflow.txt
- 23_administration/10_archives.txt
- 23_administration/20_policy_server.txt
- 23_administration/80_user_management.txt
- 4_advanced_usage/70_server_rest_api.txt
- 4_advanced_usage/77_distributed_rudder.txt
- 4_advanced_usage/90_server_migration.txt
- 5_references/10_server_data_workflow.txt
- getting-started/getting-started.txt
http://www.rudder-project.org/redmine/issues/6649
> Fixes #6649: Check the spelling and grammar of the 3.0 manual

- 6_handbook/15_migration_backup_restore.txt
http://www.rudder-project.org/redmine/issues/6664
> Fixes #6664: Restore procedures has service name mistyped

- 00_introduction/22_architecture_nodes.txt
http://www.rudder-project.org/redmine/issues/6704
> Fixes #6704: Add Debian 8 support in the specs for Rudder nodes

- 23_administration/60_technique_upgrade.txt
https://www.rudder-project.org/redmine/issues/6764
> Fixes #6764: Outdated download link in the manual

- 00_introduction/21_architecture_root_server.txt
- 00_introduction/22_architecture_nodes.txt
- 6_handbook/20_application_tuning.txt
https://www.rudder-project.org/redmine/issues/6779
> Fixes #6779: The documentation should reflect the changes done in /etc/default for rudder-jetty and rudder-slapd

- 00_introduction/22_architecture_nodes.txt
- 10_install_server/11_install_root_server_debian.txt
- 10_install_server/12_install_root_server_rhel.txt
- 10_install_server/13_install_root_server_sles.txt
- 11_install_agent/30_install_agent_suse.txt
- 12_upgrade/00_upgrade.txt
- 12_upgrade/05_caution.txt
- 12_upgrade/20_upgrade_rhel.txt
- rudder-doc.txt
https://www.rudder-project.org/redmine/issues/6908
> Fixes #6908: Finish 3.1 doc update

- 6_handbook/20_application_tuning.txt
https://www.rudder-project.org/redmine/issues/6921
> Fixes #6921: Rudder doc does not build due to a broken link

- 23_administration/10_archives.txt
https://www.rudder-project.org/redmine/issues/6909
> Fixes #6909: Wrong hierachy in archives section of the manual

- 6_handbook/15_migration_backup_restore.txt
https://www.rudder-project.org/redmine/issues/6778
> Fixes #6778: Broken asciidoc list formatting

- 10_install_server/11_install_root_server_debian.txt
- 10_install_server/12_install_root_server_sles.txt
- 10_install_server/13_install_root_server_centos_rhel.txt
https://www.rudder-project.org/redmine/issues/6603
> Fixes #6603: Improve the readability of the server installation section of the manual

- 00_introduction/22_architecture_root_server.txt
- 6_handbook/20_application_tuning.txt
https://www.rudder-project.org/redmine/issues/7081
> Fixes #7081: Improve rudder server requirements formatting

- 4_advanced_usage/10_node_management.txt
https://www.rudder-project.org/redmine/issues/7082
> Fixes #7082: Missing documentation about how to completelly reinitialise a node

- template/common/css/positioning.css
https://www.rudder-project.org/redmine/issues/7120
> Fixes #7120: Remove uneeded and un-existent file from webhelp css

- 10_install_server/12_install_root_server_rhel.txt
- 10_install_server/13_install_root_server_sles.txt
https://www.rudder-project.org/redmine/issues/7113
> Fixes #7113: Improve the readability of the server installation section of the manual for 3.0

- Makefile
- rudder-doc.txt
https://www.rudder-project.org/redmine/issues/7111
> Fixes #7111: Build the html version of the rudder man page into the manual

- Makefile
https://www.rudder-project.org/redmine/issues/7332
> Fixes #7332: rudder-doc 3.1 publishes 3.0 man pages

- Makefile
https://www.rudder-project.org/redmine/issues/7339
> Broken doc because of missing Makefile dependencies

- 4_advanced_usage/30_technique_creation.txt
http://www.rudder-project.org/redmine/issues/6305
> Fixes #6305: Add a section about ncf-builder and its integration wihin Rudder

- rudder-doc.txt
http://www.rudder-project.org/redmine/issues/7572
> Fixes #7572: Remove reference to AGPL from rudder doc

- 4_advanced_usage/30_technique_creation.txt
http://www.rudder-project.org/redmine/issues/7551
> Fixes #7551: Some titles broken in the documentation

- 00_introduction/22_architecture_nodes.txt
- 10_install_server/11_install_root_server_debian.txt
- 10_install_server/12_install_root_server_rhel.txt
- 10_install_server/13_install_root_server_sles.txt
- 11_install_agent/10_install_agent_debian.txt
- 11_install_agent/20_install_agent_rhel.txt
- 11_install_agent/30_install_agent_suse.txt
- 12_upgrade/00_upgrade.txt
- 12_upgrade/05_caution.txt
- 12_upgrade/10_upgrade_debian.txt
- 12_upgrade/20_upgrade_rhel.txt
- 12_upgrade/30_upgrade_suse.txt
- rudder-doc.txt
http://www.rudder-project.org/redmine/issues/7648
> Fixes #7648: Update documentation for 3.2

- Makefile
https://www.rudder-project.org/redmine/issues/6762
> Fixes #6762: Add a task to the ci to build the rudder man in html and man versions

- Makefile
https://www.rudder-project.org/redmine/issues/7704
> Fixes #7704: Rudder man page should be in section 8

- 00_introduction/30_architecture_network.txt
- glossary/port-5310.txt
https://www.rudder-project.org/redmine/issues/7712
> Fixes #7712: Document the use of port 5310 for rudder server debug

- 00_introduction/21_architecture_nodes.txt
http://www.rudder-project.org/redmine/issues/7650
> Fixes #7650: Document AIX support in Rudder manual

- 10_install_server/19_validation.txt
- 6_handbook/20_application_tuning.txt
https://www.rudder-project.org/redmine/issues/7220
> Fixes #7220: Document nofiles dependency for syslog/tcp on master and relays

- 12_upgrade/05_caution.txt
- 6_handbook/20_application_tuning.txt
https://www.rudder-project.org/redmine/issues/7728
> Fixes #7728: Document how to switch to UDP for reporting when upgrading to >= 3.1

- 00_introduction/22_architecture_nodes.txt
https://www.rudder-project.org/redmine/issues/7727
> Fixes #7727: Add AIX versions to the list of supported systems

- 10_install_server/12_install_root_server_sles.txt
- 10_install_server/snippets/zypper_segfault.txt.snippet
- 11_install_agent/30_install_agent_suse.txt
https://www.rudder-project.org/redmine/issues/7652
> Fixes #7652: Document the zypper segfault when installing Rudder packages locally

- 23_administration/992_inventory.txt
- 4_advanced_usage/77_distributed_rudder.txt
https://www.rudder-project.org/redmine/issues/7812
> Fixes #7812: Fix use links containing emphasized keywords in manual

- 23_administration/991_monitoring.txt
https://www.rudder-project.org/redmine/issues/7731
> Fixes #7731: Add a section in administration about integration with other tools for 3.1

- 23_administration/991_monitoring.txt
https://www.rudder-project.org/redmine/issues/7808
> Fixes #7808: Add a section in administration about integration with other tools for 3.2

- 00_introduction/21_architecture_nodes.txt
- 11_install_agent/00_install_agent.txt
https://www.rudder-project.org/redmine/issues/7817
> Fixes #7817: Broken link in the manual

- 22_configuration_management/35_parameters.txt
https://www.rudder-project.org/redmine/issues/7836
> Fixes #7836: Import doc from foswiki about parametrized variable in the doc

- 12_upgrade/05_caution.txt
https://www.rudder-project.org/redmine/issues/7823
> Fixes #7823: Missing change for 3.2 in manual

- 4_advanced_usage/10_node_management.txt
https://www.rudder-project.org/redmine/issues/6231
> Fixes #6231: Document that when we reduce the run interval of nodes, \"no data\" may be wrongly reported

- Makefile
- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/7886
> Fixes #7886: Improve appearance of the webhelp doc - changes for 3.0

- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/7905
> Fixes #7905: Broken API doc link

- rudder-doc.txt
- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/7887
> Fixes #7887: Improve appearance of the webhelp doc - changes for 3.1

- rudder-doc.txt
- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/7888
> Fixes #7888: Improve appearance of the webhelp doc - changes for 3.2

- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/8059
> Fixes #8059: Mark 3.1 as ESR in the doc header

- 10_install_server/snippets/zypper_segfault.txt.snippet
https://www.rudder-project.org/redmine/issues/8097
> Fixes #8097: Explain the SLES 12 case in the zypper segfault section

- 6_handbook/20_application_tuning.txt
- 7_troubleshooting/00_troubleshooting_intro.txt
- 7_troubleshooting/01_common_issues.txt
https://www.rudder-project.org/redmine/issues/7711
> Fixes #7711: Add \"Troubleshooting\" section

- 22_configuration_management/36_compliance.txt
- 7_troubleshooting/01_common_issues.txt
https://www.rudder-project.org/redmine/issues/8204
> Fixes #8204: Adapt \"Troubleshooting\" section for 3.0

- 10_install_server/12_install_root_server_rhel.txt
- 11_install_agent/20_install_agent_rhel.txt
https://www.rudder-project.org/redmine/issues/7976
> Fixes #7976: rudder doc can be misleading on the repo to use for Centos/RHEL

- 7_troubleshooting/01_common_issues.txt
https://www.rudder-project.org/redmine/issues/7896
> Fixes #7896: Adapt \"Troubleshooting\" section for 3.1

- 00_introduction/21_architecture_root_server.txt
- 00_introduction/22_architecture_nodes.txt
https://www.rudder-project.org/redmine/issues/8200
> Fixes #8200: Create packages for Ubuntu 16.04

- 5_references/50_generic_methods.txt
https://www.rudder-project.org/redmine/issues/8227
> Fixes #8227: Add a quick introduction before generic methods documentation

- tools/ncf_doc_rudder.py
https://www.rudder-project.org/redmine/issues/8220
> Fixes #8220: Show deprecation in generic methods documentation

- 25_administration/60_technique_upgrade.txt
https://www.rudder-project.org/redmine/issues/8291
> Fixes #8291: Document easier way to reload techniques after upgrade

- 10_installation/05_requirements/05_requirements.txt
https://www.rudder-project.org/redmine/issues/8303
> Fixes #8303: Broken xml output after #8233

- 10_installation/10_install_server/13_install_root_server_centos_rhel.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
https://www.rudder-project.org/redmine/issues/8298
> Fixes #8298: rudder doc can be misleading on the repo to use for Centos/RHEL fix typo

- 10_installation/05_requirements/22_architecture_root_server.txt
https://www.rudder-project.org/redmine/issues/8297
> Fixes #8297: Documentation wrongly states default report TTL is 30 days

- 10_installation/12_install_relay.txt
https://www.rudder-project.org/redmine/issues/7889
> Fixes #7889: Move Relay doc to the install section

- 5_references/60_man_pages.txt
- Makefile
- rudder-doc.txt
https://www.rudder-project.org/redmine/issues/8332
> Fixes #8332: Move man pages into the reference section

- 12_upgrade/00_upgrade.txt
- 12_upgrade/10_upgrade_debian.txt
- 12_upgrade/20_upgrade_centos_rhel.txt
- 12_upgrade/30_upgrade_suse.txt
- 12_upgrade/60_technique_upgrade.txt
https://www.rudder-project.org/redmine/issues/8294
> Fixes #8294: Documentation no longer clearly tells user to upgrade Techniques

- 12_upgrade/20_upgrade_rhel.txt
https://www.rudder-project.org/redmine/issues/8439
> Fixes #8439: The SLES upgrade section has a broken title syntax

- 12_upgrade/10_upgrade_debian.txt
- 12_upgrade/20_upgrade_centos_rhel.txt
- 12_upgrade/30_upgrade_suse.txt
https://www.rudder-project.org/redmine/issues/8440
> Fixes #8440: Unclear message in the upgrade doc

- 10_installation/00_introduction.txt
- 22_configuration_management/37_validation_workflow.txt
- 23_manage_your_it/20_how_to/10_Enforce_a_Line.txt
- 5_references/50_generic_methods.txt
- 7_troubleshooting/01_common_issues.txt
- Makefile
- tests/check_title_syntax.sh
https://www.rudder-project.org/redmine/issues/8443
> Fixes #8443: Add tests for doc syntax

- .gitignore
- Makefile
- tools/generate_header_info.py
- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/8450
> Fixes #8450: Use release-info to generate the manual header at creation

- tools/ncf_doc_rudder.py
https://www.rudder-project.org/redmine/issues/8524
> Fixes #8524: Fix doc after intal ncf changes (same as #8522)

- 10_installation/10_install_server/12_install_root_server_sles.txt
https://www.rudder-project.org/redmine/issues/8624
> Fixes #8624: SLES Documentation has bad package name

- 12_upgrade/00_upgrade.txt
- 12_upgrade/05_caution.txt
https://www.rudder-project.org/redmine/issues/8459
> Fixes #8459: Document precisely compatibility between servers and nodes in 3.2 doc

- Makefile
- README.asciidoc
- tests/check_broken_links.sh
https://www.rudder-project.org/redmine/issues/8548
WAIT FOR CI UPDATE
> Fixes #8548: Add a test for dead links on the doc

- template/common/main.js
https://www.rudder-project.org/redmine/issues/8569
> Fixes #8569: Left menu is sometimes broken when there is an anchor in the link

- requirements.txt
https://www.rudder-project.org/redmine/issues/8654
> Fixes #8654: Add linkchecker to a requirements.txt

- tests/check_broken_links.sh
https://www.rudder-project.org/redmine/issues/8727
> Fixes #8727: Display link errors in doc build

- tests/check_broken_links.sh
https://www.rudder-project.org/redmine/issues/8726
> Fixes #8726: Broken link in the doc

- tests/check_title_syntax.sh
https://www.rudder-project.org/redmine/issues/8733
> Fixes #8733: Add a test for maximum title level

- Makefile
https://www.rudder-project.org/redmine/issues/8732
> Fixes #8732: Broken formatting of man command sections in the doc

- 23_manage_your_it/30_security/00_intro.txt
- 23_manage_your_it/30_security/10_policy_security.txt
https://www.rudder-project.org/redmine/issues/8607
> Fixes #8607: 

- Makefile
https://www.rudder-project.org/redmine/issues/8788
> Fixes #8788: Documentation makefile fails to update git repos (git pull *before* changing branch)

- Makefile
https://www.rudder-project.org/redmine/issues/8789
> Fixes #8789: Documentation makefile fails to update git repos (git pull *before* changing branch) - 3.1 branch

- 12_upgrade/70_migrating_relays.txt
https://www.rudder-project.org/redmine/issues/6226
> Fixes #6226: Document migration to relays using the package

- 4_advanced_usage/75_separate_database.txt
https://www.rudder-project.org/redmine/issues/8847
> Fixes #8847: Document the usage of a separate database from Rudder server root

- xsl/index.html.tpl
https://www.rudder-project.org/redmine/issues/8883
> Fixes #8883:  Generate a custom index page for the manual - 3.1 changes

- 10_installation/10_install_server/11_install_root_server_debian.txt
- 10_installation/10_install_server/12_install_root_server_sles.txt
- 10_installation/10_install_server/13_install_root_server_centos_rhel.txt
- 10_installation/10_install_server/snippets/apt_key.txt.snippet
- 10_installation/10_install_server/snippets/rpm_key.txt.snippet
- 10_installation/11_install_agent/10_install_agent_debian.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
- 10_installation/11_install_agent/30_install_agent_suse.txt
https://www.rudder-project.org/redmine/issues/8864
> Fixes #8864: Safe setup of the Rudder repo in the manual

- 4_advanced_usage/75_separate_database.txt
http://www.rudder-project.org/redmine/issues/8880
> Fixes #8880: Improve the documentation for a separate database

- 4_advanced_usage/75_separate_database.txt
https://www.rudder-project.org/redmine/issues/8898
> Fixes #8898: Clear caches after restarting rudder in separate database setup doc

- 12_upgrade/20_upgrade_rhel.txt
- 12_upgrade/60_technique_upgrade.txt
- 4_advanced_usage/30_technique_creation.txt
- 6_handbook/20_application_tuning.txt
- tests/check_broken_links.sh
https://www.rudder-project.org/redmine/issues/8849
> Fixes #8849: Normalize prompt/command display in the doc

- 10_installation/10_install_server/11_install_root_server_debian.txt
- 10_installation/10_install_server/12_install_root_server_sles.txt
- 10_installation/10_install_server/13_install_root_server_centos_rhel.txt
- 10_installation/11_install_agent/10_install_agent_debian.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
- 10_installation/11_install_agent/30_install_agent_suse.txt
- 12_upgrade/00_upgrade.txt
- 12_upgrade/05_caution.txt
- 12_upgrade/10_upgrade_debian.txt
- 12_upgrade/20_upgrade_rhel.txt
- 12_upgrade/30_upgrade_suse.txt
- Makefile
- rudder-doc.txt
- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/8927
> Fixes #8927: Prepare manual for 4.0

- Makefile
https://www.rudder-project.org/redmine/issues/8931
> Fixes #8931: The manual cannot build master but only branched versions

- tools/generate_dynamic_content.py
https://www.rudder-project.org/redmine/issues/8937
> Fixes #8937: Wrong display of Rudder versions in the doc

- template/common/css/positioning.css
https://www.rudder-project.org/redmine/issues/8551
> Fixes #8551: Change the header bar of the manual to match #8359

- template/common/css/positioning.css
https://www.rudder-project.org/redmine/issues/8897
> Fixes #8897: The search bar sometimes hides the page title in webhelp doc

- template/common/css/positioning.css
https://www.rudder-project.org/redmine/issues/8917
> Fixes #8917: Code blocks in the doc overflow the page width

- 4_advanced_usage/40_node_properties.txt
- 4_advanced_usage/55_node_properties_in_directives.txt
https://www.rudder-project.org/redmine/issues/9152
> Fixes #9152: Document node properties usage

- 4_advanced_usage/50_script_in_directives.txt
https://www.rudder-project.org/redmine/issues/9190
> Fixes #9190: Script evaluation is not limited to password fields anymore

- 21_node_management/22_search_nodes.txt
https://www.rudder-project.org/redmine/issues/9210
> Fixes #9210: The quicksearch "in" keyword is "enabled" and not "isenabled"

- 12_upgrade/00_upgrade.txt
- 12_upgrade/05_caution.txt
https://www.rudder-project.org/redmine/issues/9305
> Fixes #9305: Document agent-server compatibility limits for 4.0

- Makefile
https://www.rudder-project.org/redmine/issues/9393
> Fixes #9393: Use release info to get ncf version to use in doc

- 10_installation/05_requirements/21_architecture_nodes.txt
- 10_installation/05_requirements/22_architecture_root_server.txt
https://www.rudder-project.org/redmine/issues/9408
> Fixes #9408: Update list of supported OSes in the manual

- 10_installation/10_install_server/13_install_root_server_centos_rhel.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
https://www.rudder-project.org/redmine/issues/9422
> Fixes #9422: Update documentation to have version independant repo

- Makefile
https://www.rudder-project.org/redmine/issues/9396
> Fixes #9396: Broken manual build due to missing 4.0 repo

- 4_advanced_usage/45_node_properties_in_directives.txt
https://www.rudder-project.org/redmine/issues/9466
> Fixes #9466: Broken doc build

- 12_upgrade/20_upgrade_rhel.txt
https://www.rudder-project.org/redmine/issues/9439
> Fixes #9439: Use $releasever in upgrade section for RHEL

- template/common/css/positioning.css
https://www.rudder-project.org/redmine/issues/9516
> Fixes #9516: Remove bottom border of doc header

- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/9525
> Fixes #9525: Remove gradient background in tabs in embedded html doc

- tools/generate_dynamic_content.py
https://www.rudder-project.org/redmine/issues/9564
> Fixes #9564: Build final doc for releases in rc status

- 10_installation/05_requirements/05_requirements.txt
- glossary/port-80.txt
http://www.rudder-project.org/redmine/issues/9567
> Fixes #9567: Mention port 80 in manual

- 8_reference/73_techniques_best_practices.txt
https://www.rudder-project.org/redmine/issues/9594
> Fixes #9594: Missing newline at the end of 73_techniques_best_practices.txt

- 8_reference/71_reports.txt
https://www.rudder-project.org/redmine/issues/9595
> Fixes #9595: Missing points in reports descriptions

- 8_reference/70_techniques.txt
https://www.rudder-project.org/redmine/issues/9589
> Fixes #9589: Add <FILES> doc to the manual

- 8_reference/70_techniques.txt
- 8_reference/73_techniques_best_practices.txt
https://www.rudder-project.org/redmine/issues/9597
> Fixes #9597: Broken links in techniques doc

- 8_reference/71_reports.txt
https://www.rudder-project.org/redmine/issues/9596
> Fixes #9596: Wrong description for result_na in reports reference

- 8_reference/72_techniques_templating.txt
https://www.rudder-project.org/redmine/issues/9608
> Fixes #9608: Wiki documentation broken URL

- 6_handbook/20_application_tuning.txt
https://www.rudder-project.org/redmine/issues/9628
> Fixes #9628: Bad file indicated in Java memory config chapter

- 23_manage_your_it/30_security/10_policy_security.txt
https://www.rudder-project.org/redmine/issues/9638
> Fixes #9638: Update doc for the new server-node protocol

- .gitignore
https://www.rudder-project.org/redmine/issues/9570
> Fixes #9570: Make rudder-doc gitignore more complete

- 25_administration/30_plugins.txt
https://www.rudder-project.org/redmine/issues/9721
> Fixes #9721: Bad plugin installation info on doc

- Makefile
- rudder-doc.txt
- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/9753
> Fixes #9753: Change doc for 4.1

- 4_advanced_usage/45_node_properties_in_directives.txt
https://www.rudder-project.org/redmine/issues/9800
> Fixes #9800: Missing "default =" word in node properties expansion documention

- 3_usecases/0_usecases_intro.txt
https://www.rudder-project.org/redmine/issues/9770
> Fixes #9770: Document the usecases for audit/enforce modes

- 22_configuration_management/40_policy_mode.txt
- 23_manage_your_it/00_manage_your_it.txt
https://www.rudder-project.org/redmine/issues/9668
> Fixes #9668: Document the Audit mode

- 3_usecases/0_usecases_intro.txt
https://www.rudder-project.org/redmine/issues/9826
> Fixes #9826: Broken tests after 9770

- 22_configuration_management/40_policy_mode.txt
https://www.rudder-project.org/redmine/issues/9827
> Fixes #9827: Broken tests after 9668

- 10_installation/10_install_server/11_install_root_server_debian.txt
- 10_installation/10_install_server/12_install_root_server_sles.txt
- 10_installation/10_install_server/13_install_root_server_centos_rhel.txt
- 10_installation/11_install_agent/10_install_agent_debian.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
- 10_installation/11_install_agent/30_install_agent_suse.txt
- 12_upgrade/00_upgrade.txt
- 12_upgrade/05_caution.txt
- 12_upgrade/10_upgrade_debian.txt
- 12_upgrade/20_upgrade_rhel.txt
- 12_upgrade/30_upgrade_suse.txt
https://www.rudder-project.org/redmine/issues/9887
> Fixes #9887: Prepare manual for 4.1

- 22_configuration_management/40_policy_mode.txt
https://www.rudder-project.org/redmine/issues/9771
> Fixes #9771: Document the overriding mechanism for policy mode

- Makefile
- qa-test
https://www.rudder-project.org/redmine/issues/9893
> Fixes #9893: Add qa-test for line breaks

- 22_configuration_management/40_policy_mode.txt
https://www.rudder-project.org/redmine/issues/9894
> Fixes #9894: Broken build of the manual in 4.0

- 8_reference/70_techniques.txt
https://www.rudder-project.org/redmine/issues/8633
> Fixes #8633: expected reports, component keys

- 8_reference/80_relay_api.txt
https://www.rudder-project.org/redmine/issues/9997
> Fixes #9997: Document the relay API

- 8_reference/73_techniques_best_practices.txt
https://www.rudder-project.org/redmine/issues/10151
> Fixes #10151: Broken link in CFEngine doc

- tools/generate_dynamic_content.py
https://www.rudder-project.org/redmine/issues/10181
> Fixes #10181: Add link to the new FAQ in the manual

- tools/generate_dynamic_content.py
https://www.rudder-project.org/redmine/issues/10187
> Fixes #10187: The link to the faq is broken

- 8_reference/73_techniques_best_practices.txt
https://www.rudder-project.org/redmine/issues/10227
> Fixes #10227: Always use "settings" and not "configuration" in technique names

- .gitignore
- 4_advanced_usage/60_server_event_hooks.txt
- Makefile
https://www.rudder-project.org/redmine/issues/10201
> Fixes #10201: Use readme from hooks to build rudder doc chapter on them

- template/common/css/positioning.css
https://www.rudder-project.org/redmine/issues/9945
> Fixes #9945: Use the lato font in the manual

- 23_manage_your_it/20_how_to/20_share_files_between_nodes.txt
https://www.rudder-project.org/redmine/issues/10278
> Fixes #10278: Document usage of file sharing between nodes

- 8_reference/74_package_format.txt
https://www.rudder-project.org/redmine/issues/10297
> Fixes #10297: Broken formatting of plugin packaging doc

- 4_advanced_usage/30_technique_creation.txt
https://www.rudder-project.org/redmine/issues/10269
> Fixes #10269: Doc about copying ncf technique to /var/rudder/ncf/local is false

- 21_node_management/22_search_nodes.txt
https://www.rudder-project.org/redmine/issues/10401
> Fixes #10401: Remove doc for the old quicksearch bar that has been removed

- 4_advanced_usage/60_new_directives_default_name.txt
https://www.rudder-project.org/redmine/issues/10398
> Fixes #10398: Missing documentation for "default-directive-names.conf" 

- xsl/index.html.tpl
https://www.rudder-project.org/redmine/issues/10593
> Fixes #10593: Broken links in 4.1 doc

- 3_basic_administration/30_plugins.txt
https://www.rudder-project.org/redmine/issues/10555
> Fixes #10555: Plugin installation doc is not up-to-date for rpkg package

- 10_installation/11_install_agent/00_install_agent.txt
https://www.rudder-project.org/redmine/issues/10622
> Fixes #10622: Docs: Reference to "TODO" that doesn't exist

- 4_advanced_usage/40_node_properties.txt
https://www.rudder-project.org/redmine/issues/10614
> Fixes #10614: Extend node property documentation for templates

- 4_advanced_usage/45_node_properties_in_directives.txt
https://www.rudder-project.org/redmine/issues/10613
> Fixes #10613: Node property documentation has error

- 6_handbook/15_migration_backup_restore.txt
https://www.rudder-project.org/redmine/issues/10639
> Fixes #10639: Backup restoration requires disabling the agent

- 4_advanced_usage/30_server_policy_generation.txt
https://www.rudder-project.org/redmine/issues/10633
> Fixes #10633: Doc: "Regenerate now" button has been renamed "Update policies"

- 4_advanced_usage/30_server_policy_generation.txt
https://www.rudder-project.org/redmine/issues/10647
> Fixes #10647: Doc: "Regenerate now" button has been renamed "Update policies"

- 10_installation/05_requirements/21_architecture_nodes.txt
https://www.rudder-project.org/redmine/issues/10656
> Fixes #10656: Supported Windows platforms are Windows Server 2008 and after

- 00_introduction/01_presentation.txt
https://www.rudder-project.org/redmine/issues/10668
> Fixes #10668: Broken build after parent ticket

- 10_installation/05_requirements/05_requirements.txt
- 10_installation/05_requirements/22_architecture_root_server.txt
- glossary/port-443-user.txt
- glossary/port-5309-node.txt
- glossary/port-5309.txt
- glossary/port-5310.txt
https://www.rudder-project.org/redmine/issues/10674
> Fixes #10674: Add relay content for requirements section

- 00_introduction/20_key_features.txt
- 00_introduction/40_architecture_and_dependencies.txt
- 42_advanced_configuration_management/30_server_policy_generation.txt
https://www.rudder-project.org/redmine/issues/10680
> Fixes #10680: Broken doc build

- 00_introduction/20_key_features.txt
https://www.rudder-project.org/redmine/issues/10682
> Fixes #10682: Broken doc build

- 10_installation/05_requirements/21_supported_architecture.txt
- 10_installation/05_requirements/22_unsupported_architecture.txt
- 10_installation/05_requirements/23_cloud.txt
- 10_installation/05_requirements/30_hardware_specifications.txt
https://www.rudder-project.org/redmine/issues/10679
> Fixes #10679: Document fully and partially supported OS

- 00_introduction/20_key_features.txt
https://www.rudder-project.org/redmine/issues/10681
> Fixes #10681: Complete documentation introduction

- 00_introduction/01_presentation.txt
- 10_installation/05_requirements/00_intro.txt
- 10_installation/05_requirements/05_requirements.txt
- 10_installation/05_requirements/21_supported_architecture.txt
- 10_installation/05_requirements/23_cloud.txt
- 10_installation/05_requirements/30_hardware_specifications.txt
- 10_installation/10_install_server/00_install_intro.txt
- 10_installation/11_install_agent/00_install_agent.txt
- 30_basic_administration/30_plugins.txt
- 80_extension_and_integration/00_intro.txt
- 80_extension_and_integration/20_Rudder_plugins.txt
- 80_extension_and_integration/40_Rudder_Integration.txt
https://www.rudder-project.org/redmine/issues/10688
> Fixes #10688: Use "-" in place of "_" in named reference in doc

- 22_configuration_management/38_technique_editor.txt
https://www.rudder-project.org/redmine/issues/10694
> Fixes #10694: Add an example of using a condition in the Technique creation tutorial

- 00_introduction/20_key_features.txt
https://www.rudder-project.org/redmine/issues/10696
> Fixes #10696: Missing link toward technique editor in intro "extensibility"

- 10_installation/04_quick_install.txt
https://www.rudder-project.org/redmine/issues/10691
> Fixes #10691: Missing paragraph about rudder-setup installation

- 22_configuration_management/38_technique_editor.txt
https://www.rudder-project.org/redmine/issues/10699
> Fixes #10699: Fix details in Technique editor doc

- 10_installation/05_requirements/30_hardware_specifications.txt
- 23_configuration_management/31_techniques.txt
https://www.rudder-project.org/redmine/issues/10698
> Fixes #10698: Update server requirement with load test data

- 30_basic_administration/80_user_management.txt
https://www.rudder-project.org/redmine/issues/10700
> Fixes #10700: Documentation build broken

- xsl/index.html.tpl
https://www.rudder-project.org/redmine/issues/10701
> Fixes #10701: Improve doc index and header menu

- 22_configuration_management/38_technique_editor.txt
https://www.rudder-project.org/redmine/issues/10710
> Fixes #10710: Missing information in Technique editor doc

- xsl/index.html.tpl
https://www.rudder-project.org/redmine/issues/10730
> Fixes #10730: Broken links in doc

- 10_installation/05_requirements/22_architecture_root_server.txt
- 6_handbook/20_application_tuning.txt
https://www.rudder-project.org/redmine/issues/10744
> Fixes #10744: Document correctly memory usage 

- xsl/index.html.tpl
https://www.rudder-project.org/redmine/issues/10760
> Fixes #10760: Update FAQ links in the doc

- 12_upgrade/05_caution.txt
https://www.rudder-project.org/redmine/issues/10811
> Fixes #10811: Missing doc about required agent version for audit mode

- 80_extension_and_integration/40_Rudder_Integration.txt
https://www.rudder-project.org/redmine/issues/10854
> Fixes #10854: Document the usage of the ansible plugin

- 12_upgrade/05_caution.txt
https://www.rudder-project.org/redmine/issues/10833
> Fixes #10833: Document renaming of /opt/rudder/etc/ssl/rudder-webapp.crt in 4.1

- 12_upgrade/05_caution.txt
https://www.rudder-project.org/redmine/issues/11002
> Fixes #11002: Style broken in documention: upgrade_from_rudder_3_1_3_2_or_4_0

- 43_advanced_administration/15_migration_backup_restore.txt
https://www.rudder-project.org/redmine/issues/11127
> Fixes #11127: Wrong doc for restore of Rudder ldap on 4.1

- 10_installation/04_quick_install.txt
https://www.rudder-project.org/redmine/issues/11136
> Fixes #11136: Typo in rudder-setup usage in documentation

- 25_administration/991_monitoring.txt
https://www.rudder-project.org/redmine/issues/11107
> Fixes #11107: Compliance logfile parsing regex

- 10_installation/10_install_server/11_install_root_server_debian.txt
- 10_installation/10_install_server/12_install_root_server_sles.txt
- 10_installation/10_install_server/13_install_root_server_centos_rhel.txt
- 10_installation/11_install_agent/10_install_agent_debian.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
- 10_installation/11_install_agent/30_install_agent_suse.txt
- 12_upgrade/00_upgrade.txt
- 12_upgrade/05_caution.txt
- 12_upgrade/10_upgrade_debian.txt
- 12_upgrade/20_upgrade_rhel.txt
- 12_upgrade/30_upgrade_suse.txt
- Makefile
- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/11198
> Fixes #11198: Update doc for 4.2

- rudder-doc.txt
https://www.rudder-project.org/redmine/issues/11204
> Fixes #11204: Missing change in doc title for 4.2

- 8_reference/71_reports.txt
https://www.rudder-project.org/redmine/issues/11043
> Fixes #11043: Reference for reports table is broken

- 10_installation/10_install_server/11_install_root_server_debian.txt
- 10_installation/10_install_server/12_install_root_server_sles.txt
https://www.rudder-project.org/redmine/issues/11162
> Fixes #11162: Put warnings (about dependencies for example) before install/upgrade instructions

- Makefile
https://www.rudder-project.org/redmine/issues/11305
> Fixes #11305: Missong doc about latest hooks in the manual

- 90_reference/71_reports.txt
https://www.rudder-project.org/redmine/issues/11208
> Fixes #11208: Same as parent for 4.1

- 23_configuration_management/36_compliance.txt
https://www.rudder-project.org/redmine/issues/11339
> Fixes #11339: Correct bad link in doc

- 23_configuration_management/36_compliance.txt
https://www.rudder-project.org/redmine/issues/11342
> Fixes #11342: Add link toward slack notification connector

- 4_advanced_usage/35_directive_ordering.txt
https://www.rudder-project.org/redmine/issues/11289
> Fixes #11289: Missing documentation on Directive ordering

- 10_installation/05_requirements/21_supported_architecture.txt
https://www.rudder-project.org/redmine/issues/11365
> Fixes #11365: Update doc for 4.2

- 10_installation/05_requirements/21_supported_architecture.txt
https://www.rudder-project.org/redmine/issues/11382
> Fixes #11382: Document debian 9 support for 4.1

- 90_reference/40_build_agent.txt
https://www.rudder-project.org/redmine/issues/11274
> Fixes #11274: Wrong formatting in doc to build agent

- 8_reference/70_techniques.txt
https://www.rudder-project.org/redmine/issues/11579
> Fixes #11579: Dead link in doc

- 25_administration/10_archives.txt
https://www.rudder-project.org/redmine/issues/11414
> Fixes #11414: Manually restoring permissions for NCF after archive import is broken

- 10_installation/04_quick_install.txt
https://www.rudder-project.org/redmine/issues/11668
> Fixes #11668: "Quick installation" section on the Rudder doc

- 10_installation/10_install_server/20_installed_files.txt
- 90_reference/72_techniques_templating.txt
- glossary/cfengine-enterprise.txt
- glossary/port-443-nodes.txt
- glossary/port-5308.txt
https://www.rudder-project.org/redmine/issues/11669
> Fixes #11669: Remove all mention to CFEngine Enterprise in Rudder doc

- Makefile
https://www.rudder-project.org/redmine/issues/11693
> Fixes #11693: Use new ncf branches in rudder-doc

- Makefile
https://www.rudder-project.org/redmine/issues/11697
> Fixes #11697: fetch git branch before checkout when building rudder-doc

- 42_advanced_configuration_management/40_node_properties.txt
- 42_advanced_configuration_management/45_node_properties_in_directives.txt
https://www.rudder-project.org/redmine/issues/11623
> Fixes #11623: Create documentation on local node properties overide

- 42_advanced_configuration_management/40_node_properties.txt
https://www.rudder-project.org/redmine/issues/11730
> Fixes #11730: Document how to merge properties, and not simply merge them

- 4_advanced_usage/70_server_rest_api.txt
https://www.rudder-project.org/redmine/issues/11650
> Fixes #11650: Archive REST section outdated for download ZIP archive

- 10_installation/11_install_agent/10_install_agent_debian.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
- 10_installation/11_install_agent/30_install_agent_suse.txt
- 10_installation/11_install_agent/snippets/syslog.snippet
https://www.rudder-project.org/redmine/issues/11768
> Fixes #11768: Missing doc on syslog daemon

- 10_installation/05_requirements/05_requirements.txt
- 10_installation/05_requirements/22_unsupported_architecture.txt
- 95_windows/10_server_installation.txt
- 95_windows/20_agent_installation.txt
- template/common/css/positioning.css
https://www.rudder-project.org/redmine/issues/11754
> Fixes #11754: Update prerequisite and document windows plugin installation on server and agent

- 43_advanced_administration/15_migration_backup_restore.txt
https://www.rudder-project.org/redmine/issues/11177
> Fixes #11177: Restore backup documentation is not correct

- 10_installation/05_requirements/21_supported_architecture.txt
- 10_installation/10_install_server/11_install_root_server_debian.txt
- 10_installation/10_install_server/12_install_root_server_sles.txt
- 10_installation/10_install_server/13_install_root_server_centos_rhel.txt
- 10_installation/11_install_agent/10_install_agent_debian.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
- 10_installation/11_install_agent/30_install_agent_suse.txt
- 12_upgrade/00_upgrade.txt
- 12_upgrade/05_caution.txt
- 12_upgrade/10_upgrade_debian.txt
- 12_upgrade/20_upgrade_rhel.txt
- 12_upgrade/30_upgrade_suse.txt
- rudder-doc.txt
- xsl/webhelp-common.xsl
https://www.rudder-project.org/redmine/issues/12049
> Fixes #12049: Update doc for 4.3

- 4_advanced_usage/35_directive_ordering.txt
https://www.rudder-project.org/redmine/issues/11963
> Fixes #11963: Please, legitimate "Priority" usage in multi-instance directives

- 10_installation/05_requirements/21_supported_architecture.txt
https://www.rudder-project.org/redmine/issues/11854
> Fixes #11854: Clarify support for SLES12 SP2 as Root Server

- 23_configuration_management/41_technique_editor.txt
https://www.rudder-project.org/redmine/issues/12175
> Fixes #12175:  Rename class to condition in the doc

- 10_installation/11_install_agent/10_install_agent_debian.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
- 10_installation/11_install_agent/30_install_agent_suse.txt
https://www.rudder-project.org/redmine/issues/11927
> Fixes #11927: Missing configuration instructions at the end of node install documentation

- xsl/index.html.tpl
https://www.rudder-project.org/redmine/issues/12363
> Fixes #12363: Remove references to foswiki in the doc

- 10_installation/10_install_server/11_install_root_server_debian.txt
- 30_basic_administration/50_services_administration.txt
- 30_basic_administration/70_server_rest_api.txt
https://www.rudder-project.org/redmine/issues/12347
> Fixes #12347: Update doc for 4.3

- 95_windows/10_server_installation.txt
- 95_windows/20_agent_installation.txt
- 95_windows/60_techniques.txt
- 95_windows/70_agent_cli.txt
https://www.rudder-project.org/redmine/issues/12393
> Fixes #12393: Add docs about Windows agent logging

- rudder-by-example/src/SUMMARY.adoc
- rudder-by-example/src/application/install-exe-or-msi.adoc
- rudder-by-example/src/files/advanced-file-templating.adoc
- rudder-by-example/src/files/edition-one-line.adoc
- rudder-by-example/src/system/manage-registry.adoc
https://www.rudder-project.org/redmine/issues/12611
> Fixes #12611: Typos in rudder-by-example

- 90_reference/70_techniques.txt
- 90_reference/72_techniques_templating.txt
https://www.rudder-project.org/redmine/issues/11832
> Fixes #11832: Document multiversionned technique

- 30_basic_administration/30_plugins.txt
https://www.rudder-project.org/redmine/issues/12771
> Fixes #12771: Documentaiton should use full path to rudder-pkg for command examples

- 95_windows/10_server_installation.txt
- 95_windows/20_agent_installation.txt
https://www.rudder-project.org/redmine/issues/12748
> Fixes #12748: Adding missings informations for Windows plugin installation

- 10_installation/10_install_server/13_install_root_server_centos_rhel.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
- 12_upgrade/20_upgrade_rhel.txt
https://www.rudder-project.org/redmine/issues/12802
> Fixes #12802: Change the documentation to tell the user to use the gpg key from the root path

- 90_reference/74_package_format.txt
https://www.rudder-project.org/redmine/issues/12810
> Fixes #12810: Add binary dependency to rpkg format documentation

- 10_installation/05_requirements/21_supported_architecture.txt
https://www.rudder-project.org/redmine/issues/12756
> Fixes #12756: Rudder doc 4.3 fails to list the supported SLES for the nodes

- .gitignore
- Makefile
https://www.rudder-project.org/redmine/issues/12750
> Fixes #12750: Documentation for dsc ncf GM does not appear in the user manual

- 10_installation/05_requirements/21_supported_architecture.txt
https://www.rudder-project.org/redmine/issues/12854
> Fixes #12854: Missing support of Ubuntu 18.04 agent in documentation

- unified/site.yml
https://www.rudder-project.org/redmine/issues/12871
> Fixes #12871: Build antora build error

- 85_Plugins/50_node_external_reports.txt
https://www.rudder-project.org/redmine/issues/12898
> Fixes #12898: Error in Plugin section for Node external reports

- 85_Plugins/50_node_external_reports.txt
https://www.rudder-project.org/redmine/issues/12901
> Fixes #12901: Invalid ordering of elements in node external reports plugin

- site.yml
- src/reference/Makefile
https://www.rudder-project.org/redmine/issues/12962
> Fixes #12962: Build error after parent change

- 85_Plugins/10_DSC_plugin.txt
https://www.rudder-project.org/redmine/issues/12772
> Fixes #12772: Script execution must be allowed to install and use Rudder on Windows nodes

- src/reference/dependencies/Makefile
https://www.rudder-project.org/redmine/issues/12979
> Fixes #12979: rudder man page now uses .adoc extension

- src/reference/dependencies/Makefile
https://www.rudder-project.org/redmine/issues/13019
> Fixes #13019: Change version of documentation on rudder-doc

- src/rudder-by-example/modules/ROOT/pages/files/advanced-file-templating.adoc
Adding a possible configuration of sshd_config via either node properties or variable definition directives
> advanced-file-templating: Example of sshd_config

- .gitignore
- Makefile
- site.yml
https://www.rudder-project.org/redmine/issues/13068
> Fixes #13068: Use 5.0 branch

- rudder-theme/src/partials/header-content.hbs
https://www.rudder-project.org/redmine/issues/13076
> Fixes #13076: Update header bar

- src/reference/.gitignore
- src/reference/Makefile
- src/reference/modules/ROOT/pages/23_configuration_management/37_validation_workflow.adoc
- src/reference/modules/ROOT/pages/23_configuration_management/40_policy_mode.adoc
- src/reference/modules/ROOT/pages/41_advanced_node_management/11_node_install.adoc
- src/reference/modules/ROOT/pages/85_Plugins/10_DSC_plugin.adoc
- src/reference/modules/ROOT/pages/85_Plugins/47_node_properties_data_sources.adoc
- src/reference/modules/ROOT/pages/85_Plugins/60_branding.adoc
- src/reference/modules/ROOT/pages/90_reference/05_inventory_workflow.adoc
- src/reference/modules/ROOT/pages/90_reference/10_server_data_workflow.adoc
- src/reference/modules/ROOT/pages/90_reference/20_agent_data_workflow.adoc
- src/reference/modules/ROOT/pages/90_reference/39_server_install.adoc
- src/reference/modules/ROOT/pages/90_reference/70_techniques.adoc
https://www.rudder-project.org/redmine/issues/12965
> Fixes #12965: Fix graphviz integration

- src/reference/modules/ROOT/pages/43_advanced_administration/10_database_maintenance.adoc
- src/reference/modules/ROOT/pages/43_advanced_administration/15_migration_backup_restore.adoc
- src/reference/modules/ROOT/pages/43_advanced_administration/20_application_tuning.adoc
- src/reference/modules/ROOT/pages/90_reference/10_server_data_workflow.adoc
https://www.rudder-project.org/redmine/issues/13092
> Fixes #13092: Fix code blocks inclusion 

- src/get-started/antora.yml
- src/reference/antora.yml
- src/reference/dependencies/Makefile
- src/rudder-by-example/antora.yml
https://www.rudder-project.org/redmine/issues/13102
> Fixes #13102: Sensible sources/branches for release and dev builds

- src/get-started/antora.yml
- src/reference/antora.yml
- src/rudder-by-example/antora.yml
https://www.rudder-project.org/redmine/issues/13105
> Fixes #13105: Need to quote version

- .gitignore
- Makefile
- doc-5.0.yml
- doc-5.1.yml
- site-dev.yml
- site-local.yml
- src/get-started/antora.yml
- src/rudder-by-example/antora.yml
- tests/check_broken_links.sh
https://www.rudder-project.org/redmine/issues/13110
> Fixes #13110: Make different targets for docs

- Makefile
- doc-5.0.yml
- doc-5.1.yml
https://www.rudder-project.org/redmine/issues/13115
> Fixes #13115: Use tar.gz instead of zip

- src/reference/tools/generate-nav.py
https://www.rudder-project.org/redmine/issues/13122
> Fixes #13122: Remove underscores from the end of the id

- Makefile
- rudder-theme/src/partials/header-content.hbs
- site-dev.yml
- site-local.yml
- site.yml
- tests/check_broken_links.sh
https://www.rudder-project.org/redmine/issues/13126
> Fixes #13126: Generate redirection info to latest stable doc

- rudder-theme/src/partials/navigation-explore.hbs
https://www.rudder-project.org/redmine/issues/13130
> Fixes #13130: Add links to 4.1 and 4.3 docs

- rudder-theme/src/partials/footer-scripts.hbs
- rudder-theme/src/partials/head-scripts.hbs
- rudder-theme/src/partials/header-content.hbs
https://www.rudder-project.org/redmine/issues/13093
> Fixes #13093: Add a search field

- rudder-theme/docs/modules/ROOT/pages/list-styles.adoc
- rudder-theme/preview-site-src/ui-model.yml
- rudder-theme/src/css/base.css
- rudder-theme/src/css/doc.css
- rudder-theme/src/css/navigation-explore.css
- rudder-theme/src/css/navigation-menu.css
- rudder-theme/src/css/navigation.css
- rudder-theme/src/js/01-navigation.js
- rudder-theme/src/layouts/default.hbs
- rudder-theme/src/partials/breadcrumbs.hbs
- rudder-theme/src/partials/header-content.hbs
- rudder-theme/src/partials/main.hbs
- rudder-theme/src/partials/navigation.hbs
https://www.rudder-project.org/redmine/issues/13156
> Fixes #13156: Upgrade ui from default theme

- Makefile
https://www.rudder-project.org/redmine/issues/13140
> Fixes #13140: Build a .htacces including redirect

- src/get-started/modules/ROOT/pages/advanced-configuration/compliance.adoc
- src/get-started/modules/ROOT/pages/advanced-configuration/rules.adoc
- src/get-started/modules/ROOT/pages/advanced-configuration/technique.adoc
- src/get-started/modules/ROOT/pages/configuration-policies/apply.adoc
- src/get-started/modules/ROOT/pages/configuration-policies/directive.adoc
- src/get-started/modules/ROOT/pages/configuration-policies/policy-mode.adoc
- src/get-started/modules/ROOT/pages/configuration-policies/technique.adoc
- src/get-started/modules/ROOT/pages/environment/index.adoc
- src/get-started/modules/ROOT/pages/node-management/data.adoc
- src/get-started/modules/ROOT/pages/node-management/group.adoc
- src/get-started/modules/ROOT/pages/node-management/node.adoc
- src/rudder-by-example/modules/ROOT/nav.adoc
- src/rudder-by-example/modules/ROOT/pages/application/index.adoc
- src/rudder-by-example/modules/ROOT/pages/files/edition-one-line.adoc
- src/rudder-by-example/modules/ROOT/pages/files/index.adoc
- src/rudder-by-example/modules/ROOT/pages/system/index.adoc
https://www.rudder-project.org/redmine/issues/13161
> Fixes #13161: Use first level title for each page in get-started and by-example

- rudder-theme/src/layouts/404.hbs
- rudder-theme/src/layouts/default.hbs
- rudder-theme/src/partials/head-scripts.hbs
- rudder-theme/src/partials/navigation-explore.hbs
https://www.rudder-project.org/redmine/issues/13163
> Fixes #13163: Improve doc build config

- src/get-started/modules/ROOT/_attributes.adoc
- src/get-started/modules/ROOT/pages/home.adoc
https://www.rudder-project.org/redmine/issues/13134
> Fixes #13134: Make a nice home page

- tests/check_broken_links.sh
https://www.rudder-project.org/redmine/issues/13167
> Fixes #13167: Broken link in dev doc after parent

- Makefile
- doc-5.0.yml
- doc-5.1.yml
https://www.rudder-project.org/redmine/issues/13240
> Fixes #13240: Use the right file organizationin build directory

- rudder-theme/src/css/custom.css
- src/reference/tools/generate-nav.py
https://www.rudder-project.org/redmine/issues/13208
> Fixes #13208: Fix UI bugs after css update

- rudder-theme/src/css/custom.css
- rudder-theme/src/img/menu-nav-close.svg
- rudder-theme/src/img/menu-nav.svg
https://www.rudder-project.org/redmine/issues/13051
> Fixes #13051: Indicate more clearly that there are different documents in the same site

- src/get-started/modules/ROOT/pages/home.adoc
https://www.rudder-project.org/redmine/issues/13281
> Fixes #13281: Fix install links in home page

- rudder-theme/src/css/custom.css
https://www.rudder-project.org/redmine/issues/13271
> Fixes #13271: Improve appearance of text blocks

- src/reference/dependencies/Makefile
https://www.rudder-project.org/redmine/issues/13306
> Fixes #13306: Missing repo init in parent

- src/reference/dependencies/Makefile
https://www.rudder-project.org/redmine/issues/13308
> Fixes #13308: Missing mkdir in parent

- src/reference/modules/installation/pages/_partials/apt_key.adoc
- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/rpm_key.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
https://www.rudder-project.org/redmine/issues/13382
> Fixes #13382: Use repository.rudder.io in 5.0 doc

- src/reference/modules/administration/pages/monitoring.adoc
- src/reference/modules/administration/pages/multi_server.adoc
- src/reference/modules/administration/pages/performance.adoc
- src/reference/modules/administration/pages/procedures.adoc
- src/reference/modules/administration/pages/server.adoc
- src/reference/modules/administration/pages/users.adoc
- src/reference/modules/plugins/pages/index.adoc
https://www.rudder-project.org/redmine/issues/13284
> Fixes #13284: Continue the doc cleaning on administration chapter

- Makefile
https://www.rudder-project.org/redmine/issues/13449
> Fixes #13449: Make the current -> 5.0 redirect work in Rudder

- src/rudder-by-example/modules/ROOT/pages/application/install-exe-or-msi.adoc
- src/rudder-by-example/modules/ROOT/pages/files/advanced-file-templating.adoc
- src/rudder-by-example/modules/ROOT/pages/files/edition-replace-line.adoc
- src/rudder-by-example/modules/ROOT/pages/system/manage-registry.adoc
https://www.rudder-project.org/redmine/issues/13452
> Fixes #13452: Rudder by example cleanup

- rudder-theme/src/partials/header-content.hbs
https://www.rudder-project.org/redmine/issues/13264
> Fixes #13264: Rework header menu

- src/rudder-by-example/modules/ROOT/pages/files/advanced-file-templating.adoc
- src/rudder-by-example/modules/ROOT/pages/files/edition-replace-line.adoc
https://www.rudder-project.org/redmine/issues/13477
> Fixes #13477: Fix rudder by example internal links

- Makefile
https://www.rudder-project.org/redmine/issues/13486
> Fixes #13486: Parent patch does not work

- Makefile
https://www.rudder-project.org/redmine/issues/13490
> Fixes #13490: htaccess for embedded doc needs to be different

- rudder-theme/src/css/navigation-menu.css
- rudder-theme/src/img/caret.svg
- rudder-theme/src/js/01-navigation.js
https://www.rudder-project.org/redmine/issues/13501
> Fixes #13501: Update theme to 1.1.1

- src/get-started/modules/ROOT/pages/home.adoc
https://www.rudder-project.org/redmine/issues/13504
> Fixes #13504: The menu should point to gitter instead of IRC

- rudder-theme/src/css/custom.css
https://www.rudder-project.org/redmine/issues/13502
> Fixes #13502: Fix appearance of titles

- rudder-theme/src/css/custom.css
https://www.rudder-project.org/redmine/issues/13506
> Fixes #13506: Level 4 are too big

- src/reference/modules/installation/pages/operating_systems.adoc
- src/reference/modules/plugins/pages/index.adoc
https://www.rudder-project.org/redmine/issues/13526
> Fixes #13526: Add information about Rudder subscription to the doc

- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
https://www.rudder-project.org/redmine/issues/13534
> Fixes #13534: Update download link in documentation

- src/reference/modules/installation/pages/_partials/apt_key.adoc
- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/rpm_key.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
https://www.rudder-project.org/redmine/issues/13541
> Fixes #13541: remove apt and rpm prefixes

- src/reference/modules/installation/pages/operating_systems.adoc
https://www.rudder-project.org/redmine/issues/13533
> Fixes #13533: Add sles 15 in 5.0 supported OS

- 10_installation/05_requirements/21_supported_architecture.txt
- 10_installation/11_install_agent/20_install_agent_centos_rhel.txt
https://www.rudder-project.org/redmine/issues/13624
> Fixes #13624: Document Amazon Linux compatibility

- src/reference/modules/installation/pages/agent/rhel.adoc
https://www.rudder-project.org/redmine/issues/13626
> Fixes #13626: Same for 5.0

- 23_configuration_management/41_technique_editor.txt
https://www.rudder-project.org/redmine/issues/13756
> Fixes #13756: Broken doc build due to broken link

- 23_configuration_management/41_technique_editor.txt
https://www.rudder-project.org/redmine/issues/13757
> Fixes #13757: Broken doc build due to broken link - 4.3 version

- rudder-theme/src/partials/head-scripts.hbs
https://www.rudder-project.org/redmine/issues/13520
> Fixes #13520: No favicon for Rudder doc on embeded doc

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/11016
> Fixes #11016: Document port 5514 for ubuntu

- rudder-theme/src/css/custom.css
- rudder-theme/src/img/search.svg
- rudder-theme/src/partials/header-content.hbs
https://issues.rudder.io/issues/13132
> Fixes #13132: Make a nice search field and results

- src/reference/modules/usage/pages/configuration_management.adoc
https://issues.rudder.io/issues/13945
> Fixes #13945: Document some CFEngine system varialbes

- .gitignore
- Makefile
- README.adoc
- rudder-theme/src/partials/navigation-explore.hbs
- site-dev.yml
- site-local.yml
- site.yml
- src/changelogs/.gitignore
- src/changelogs/Makefile
- src/changelogs/antora.yml
- src/changelogs/dependencies/.gitignore
- src/changelogs/dependencies/Makefile
https://issues.rudder.io/issues/13928
> Fixes #13928: Render changelogs in Rudder doc

- rudder-theme/src/partials/header-content.hbs
- src/get-started/modules/ROOT/pages/home.adoc
- src/get-started/modules/ROOT/pages/next.adoc
- src/reference/modules/installation/pages/_partials/quick_agent.adoc
- src/reference/modules/installation/pages/_partials/quick_server.adoc
- src/reference/modules/installation/pages/quick_install.adoc
https://issues.rudder.io/issues/14034
> Fixes #14034: Update rudder-setup url in docs

- rudder-theme/src/partials/header-content.hbs
- src/reference/modules/ROOT/pages/videos.adoc
https://issues.rudder.io/issues/14029
> Fixes #14029: Add a page for videos about Rudder

- src/reference/Makefile
- src/reference/dependencies/.gitignore
- src/reference/dependencies/Makefile
- src/reference/dependencies/tools/ncf_doc_rudder.py
- src/reference/dependencies/tools/versions.sh
- src/reference/modules/installation/nav.adoc.src
- src/reference/modules/installation/pages/versions.adoc
https://issues.rudder.io/issues/13956
> Fixes #13956: Add a page with an array for all versions info

- tools/ncf_doc_rudder.py
https://issues.rudder.io/issues/14048
> Fixes #14048: Broken 4.1/4.3 doc build

- src/reference/modules/usage/pages/node_management.adoc
https://issues.rudder.io/issues/14126
> Fixes #14126: Use B instead of b for bytes in the doc

- src/reference/modules/usage/pages/configuration_management.adoc
https://issues.rudder.io/issues/13915
> Fixes #13915: Missing documentation for "state" and "policymode" parameter expansion

- 85_Plugins/10_DSC_plugin.txt
https://issues.rudder.io/issues/14150
> Fixes #14150: Add some known issues in the known issue of the DSC doc

- rudder-theme/src/partials/header-content.hbs
- src/get-started/modules/ROOT/pages/home.adoc
- src/reference/modules/installation/pages/operating_systems.adoc
- src/reference/modules/installation/pages/versions.adoc
- src/reference/modules/usage/pages/advanced_configuration_management.adoc
- tests/check_broken_links.sh
https://issues.rudder.io/issues/14203
> Fixes #14203: Update links in doc to rudder.io

- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
https://issues.rudder.io/issues/14262
> Fixes #14262: Remove "repository" from Rudder repository name

- Makefile
https://issues.rudder.io/issues/14284
> Fixes #14284: Roo t of webapp docs changed

- 90_reference/72_techniques_templating.txt
https://issues.rudder.io/issues/14137
> Fixes #14137: Typo in "Replacement" in Doc

- rudder-theme/src/partials/article.hbs
https://issues.rudder.io/issues/14402
> Fixes #14402: Order of links is wrong 

- src/reference/modules/installation/pages/requirements.adoc
In particular, the fact that IE11 is not supported.
> Add a paragraph on browser support

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/14409
> Fixes #14409: Document cf-serverd verbosity changes

- src/reference/Makefile
- src/reference/dependencies/Makefile
- src/reference/modules/reference/pages/man.adoc
https://issues.rudder.io/issues/14702
> Fixes #14702: Add rudder-relayd man page to the doc

- src/reference/modules/ROOT/pages/videos.adoc
https://issues.rudder.io/issues/14731
> Fixes #14731: Add 2019 CfgMgmgtCamp videos to the docs 

- src/reference/modules/administration/nav.list
- src/reference/modules/administration/pages/troubleshooting.adoc
https://issues.rudder.io/issues/14785
> Fixes #14785: Add a debugging guide page to the doc

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/14450
> Fixes #14450: Document using pg_repack to prevent large disk usage

- 30_basic_administration/10_archives.txt
https://issues.rudder.io/issues/14607
> Fixes #14607: document the behaviour of archives everything that commits everyhting in repo

- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/14842
> Fixes #14842: Disk usage in documentation is insuficiently precise 

- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/14940
> Fixes #14940: Specify that we need several codes  for Rudder server when managing a lot of nodes 

- 30_basic_administration/10_archives.txt
https://issues.rudder.io/issues/15180
> Fixes #15180: Correct archives procedure to include a 'technique reload'

- src/reference/modules/administration/pages/procedures.adoc
- src/reference/modules/installation/pages/_partials/initial_config.adoc
- src/reference/modules/reference/pages/architecture.adoc
https://issues.rudder.io/issues/15343
> Fixes #15343: Remove rudder-init from documentation

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/15443
> Fixes #15443: Update list of supported OS

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/15193
> Fixes #15193: Add upgrade note about the change of behaviour of condition_from_command starting 5.1

- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/initial_config.adoc
- src/reference/modules/installation/pages/_partials/quick_agent.adoc
- src/reference/modules/installation/pages/_partials/quick_server.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
- src/reference/modules/installation/pages/_partials/syslog.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/reference/modules/installation/pages/operating_systems.adoc
- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/15452
> Fixes #15452: Update doc for 5.1

- 5.1.yml
- Makefile
- rudder-theme/src/partials/navigation-explore.hbs
- site-dev.yml
- site.yml
- src/changelogs/antora.yml
- src/changelogs/dependencies/Makefile
- src/reference/antora.yml
https://issues.rudder.io/issues/15612
> Fixes #15612: Prepare 5.1 doc

- site.yml
https://issues.rudder.io/issues/15614
> Fixes #15614: Broken yml in parent

- 5.2.yml
- src/changelogs/antora.yml
- src/reference/antora.yml
https://issues.rudder.io/issues/15615
> Fixes #15615: Broken doc build after parent

- Makefile
https://issues.rudder.io/issues/15616
> Fixes #15616: Broken doc build after parent

- Makefile
- src/changelogs/dependencies/Makefile
https://issues.rudder.io/issues/15618
> Fixes #15618: Missing 5.0 changelog in docs

- src/reference/modules/administration/pages/performance.adoc
https://issues.rudder.io/issues/15702
> Fixes #15702: improve documentation on memory requierement

- src/reference/modules/installation/pages/_partials/relay_plugin.adoc
- src/reference/modules/installation/pages/relay/debian.adoc
- src/reference/modules/installation/pages/relay/rhel.adoc
- src/reference/modules/installation/pages/relay/sles.adoc
https://issues.rudder.io/issues/15751
> Fixes #15751: Display a warning in relay server documentatin that it needs a plugin to work

- src/reference/modules/plugins/pages/index.adoc
https://issues.rudder.io/issues/15793
> Fixes #15793: Add a section in plugin documentation about plugin installation

- src/reference/modules/installation/pages/requirements.adoc
- src/reference/modules/reference/pages/_partials/glossary/port-5310.adoc
https://issues.rudder.io/issues/14159
> Fixes #14159: 5310 is only used internally, no need to open it on the server

- rudder-theme/src/partials/navigation-explore.hbs
https://issues.rudder.io/issues/14222
> Fixes #14222: On the local rudder doc bring with the server, changelog are "access denied"

- 6.0.yml
- 6.1.yml
- Makefile
- site-dev.yml
- site.yml
- src/changelogs/dependencies/Makefile
- src/reference/dependencies/Makefile
- src/reference/modules/installation/pages/_partials/quick_agent.adoc
- src/reference/modules/installation/pages/_partials/quick_server.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/reference/modules/installation/pages/requirements.adoc
- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/15845
> Fixes #15845: Adapt doc for 6.0

- src/changelogs/antora.yml
- src/reference/antora.yml
- src/reference/modules/installation/pages/_partials/debian_repo.adoc
https://issues.rudder.io/issues/15847
> Fixes #15847: Adapt doc for 6.0 - missing changes

- src/changelogs/dependencies/Makefile
- src/reference/antora.yml
- src/reference/dependencies/Makefile
- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/quick_agent.adoc
- src/reference/modules/installation/pages/_partials/quick_server.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
https://issues.rudder.io/issues/15846
> Fixes #15846: Adapt doc for 6.1

- src/changelogs/antora.yml
https://issues.rudder.io/issues/15850
> Fixes #15850: Missing change for 5.0 changelog

- src/changelogs/antora.yml
https://issues.rudder.io/issues/15851
> Fixes #15851: Adapt changelog version for 6.1

- Makefile
https://issues.rudder.io/issues/15852
> Fixes #15852: Missing change for changelog reference version

- src/get-started/modules/ROOT/pages/home.adoc
https://issues.rudder.io/issues/15855
> Fixes #15855: Doc links in home should point to 5.0 and not 6.0

- src/reference/modules/plugins/pages/windows.adoc
https://issues.rudder.io/issues/15887
> Fixes #15887: Fix deadlink in docs

- rudder-theme/src/partials/navigation-explore.hbs
https://issues.rudder.io/issues/15889
> Fixes #15889: Add relay API to doc menu

- rudder-theme/src/partials/navigation-explore.hbs
https://issues.rudder.io/issues/15928
> Fixes #15928: Add a link to old docs

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/15972
> Fixes #15972: Document that 6.0 upgrade is only possible from 5.0

- rudder-theme/src/partials/navigation-explore.hbs
https://issues.rudder.io/issues/15973
> Fixes #15973: parent should only be displayed for reference module

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/15967
> Fixes #15967: Document tools folder removal in upgrade notes

- src/reference/.gitignore
- src/reference/Makefile
- src/reference/dependencies/.gitignore
- src/reference/dependencies/Makefile
- src/reference/dependencies/tools/ncf_doc_rudder.py
- src/reference/modules/reference/nav.list
- src/reference/modules/reference/pages/generic_methods.adoc
- src/reference/modules/reference/pages/generic_methods_guidelines.adoc
- src/reference/tools/generate-nav.py
https://issues.rudder.io/issues/16034
> Fixes #16034: Improve generic method docs

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/16073
> Fixes #16073: Add a link to the backup doc at the beginning of upgrade procedure

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/15974
> Fixes #15974: document purging of logs

- src/reference/modules/usage/pages/node_management.adoc
https://issues.rudder.io/issues/14161
> Fixes #14161: Use MB instead of mB for megabytes in the doc

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/15984
> Fixes #15984: Document that a full policy regeneration is necessary after a backup restauration

- src/get-started/modules/ROOT/pages/index.adoc
https://issues.rudder.io/issues/15408
> Fixes #15408: Missing link to beginning of the guide in getting stated home page

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/16163
> Fixes #16163: Document the need for systemd for some distributions

- rudder-theme/src/partials/navigation-explore.hbs
https://issues.rudder.io/issues/16156
> Fixes #16156: Display 6.0 as 6.0-beta in doc menu

- src/reference/modules/plugins/pages/windows.adoc
https://issues.rudder.io/issues/14633
> Fixes #14633: typo in link to generic method mustache introduced in #14446

- src/reference/modules/administration/nav.list
- src/reference/modules/administration/pages/installation_option.adoc
https://issues.rudder.io/issues/10015
> Fixes #10015: Document the usage of environment variables during installation

- src/reference/modules/administration/pages/users.adoc
https://issues.rudder.io/issues/14812
> Fixes #14812: Document that a plugin is required for user roles and LDAP authentification

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/15271
> Fixes #15271: Backup procedure documentation is incorrect

- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/16207
> Fixes #16207: In doc, we recommend using multiserver setup, while its benefit may be dubious

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/16202
> Fixes #16202: Document new reporting protocol

- src/reference/modules/administration/pages/server.adoc
- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/16284
> Fixes #16284: Document reporting protocol options

- src/changelogs/Makefile
https://issues.rudder.io/issues/16300
> Fixes #16300: Render release notes in the changelog

- src/changelogs/Makefile
https://issues.rudder.io/issues/16309
> Fixes #16309: Parent breaks changelogs

- src/changelogs/Makefile
https://issues.rudder.io/issues/16312
> Fixes #16312: Parent broke <6.0 changelogs

- rudder-theme/src/partials/navigation-explore.hbs
- src/get-started/modules/ROOT/pages/home.adoc
https://issues.rudder.io/issues/16375
> Fixes #16375: 6.0 release in docs

- src/reference/modules/installation/pages/quick_install.adoc
https://issues.rudder.io/issues/16373
> Fixes #16373: Update rudder-setup doc

- src/reference/modules/installation/pages/versions.adoc
https://issues.rudder.io/issues/16358
> Fixes #16358: Update release policy

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/16431
> Fixes #16431: Warn people that for now, upgrade of Rudder from 5.0 is broken

- src/reference/modules/installation/nav.adoc.src
- src/reference/modules/installation/pages/install_notes.adoc
https://issues.rudder.io/issues/16451
> Fixes #16451: Warn user about know bug in 6.0.1 and installation workaround

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/16487
> Fixes #16487: Document Amazon Linux support state

- src/reference/modules/plugins/pages/index.adoc
https://issues.rudder.io/issues/16545
> Fixes #16545: Install command for plugin is wrong in the doc

- src/reference/modules/installation/pages/_partials/agent_initial_config.adoc
https://issues.rudder.io/issues/16544
> Fixes #16544: Do not advise to run "rudder agent start" after installation

- src/reference/modules/administration/pages/server.adoc
https://issues.rudder.io/issues/16672
> Fixes #16672: document how to recover from partial archiving without the dsc forlder

- src/reference/modules/plugins/pages/index.adoc
- src/reference/modules/reference/nav.list
- src/reference/modules/reference/pages/plugin_format.adoc
https://issues.rudder.io/issues/16639
> Fixes #16639: Plugins architecture documentation is hard to find

- src/reference/modules/administration/pages/users.adoc
https://issues.rudder.io/issues/16724
> Fixes #16724: Add Bcrypt support informations 

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/16729
> Fixes #16729: Add upgrade note to document how to switch from previous hash function to BCrypt

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/16786
> Fixes #16786: 6.0 inventory issue fixed in 6.0.3 and not 6.0.4

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/16832
> Fixes #16832: Add upgrade notice to 6.0.3

- rudder-theme/src/partials/navigation-explore.hbs
https://issues.rudder.io/issues/16865
> Fixes #16865: Add a new index for API doc

- src/reference/modules/usage/pages/advanced_configuration_management.adoc
https://issues.rudder.io/issues/16903
> Fixes #16903: Document /var/rudder/policy-generation-info

- src/reference/modules/reference/pages/variables.adoc
https://issues.rudder.io/issues/16918
> Fixes #16918: Typo in Variable doc: hsotname

- src/reference/modules/usage/pages/advanced_node_management.adoc
https://issues.rudder.io/issues/16940
> Fixes #16940: Add DSC inventory hook documentation

- src/reference/modules/reference/nav.list
- src/reference/modules/reference/pages/jetty_server_configuration.adoc
https://issues.rudder.io/issues/16677
> Fixes #16677: Explains how to change requestHeaderSize in Rudder 5.0

- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/16970
> Fixes #16970: Broken formatting of network requirements

- src/reference/modules/reference/nav.list
- src/reference/modules/reference/pages/logs.adoc
https://issues.rudder.io/issues/16602
> Fixes #16602: Add a logs documentation page

- src/get-started/modules/ROOT/pages/node-management/node.adoc
https://issues.rudder.io/issues/17000
> Fixes #17000: Add policy server configuration to get-started

- src/reference/modules/reference/pages/generic_methods_guidelines.adoc
https://issues.rudder.io/issues/16999
> Fixes #16999: Add a reference documentation about methods writing

- src/reference/modules/plugins/pages/windows.adoc
https://issues.rudder.io/issues/17018
> Fixes #17018: Precise in the documentation that the Windows agent does not currently support HTTPS report mode

- rudder-theme/src/partials/header-content.hbs
https://issues.rudder.io/issues/17033
> Fixes #17033: Update content of docs menus

- src/reference/modules/reference/pages/variables.adoc
https://issues.rudder.io/issues/17034
> Fixes #17034: Add better documentation on how to access technique parameter within an ncf technique

- src/reference/dependencies/Makefile
https://issues.rudder.io/issues/16990
> Fixes #16990: Change path for plugin images

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/17005
> Fixes #17005: remove debian 5 from the list of supported os

- src/reference/modules/installation/nav.adoc.src
- src/reference/modules/installation/pages/dev.adoc
https://issues.rudder.io/issues/17091
> Fixes #17091: Add a page about pre-releases

- src/reference/modules/installation/pages/_partials/bcrypt.adoc
- src/reference/modules/installation/pages/_partials/relay_initial_config.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/17130
> Fixes #17130: Prepare doc for 6.1

- src/reference/modules/installation/pages/_partials/initial_config.adoc
https://issues.rudder.io/issues/17174
> Fixes #17174: Update doc for initial user account

- src/get-started/modules/ROOT/pages/home.adoc
https://issues.rudder.io/issues/17200
> Fixes #17200: Fix links in 6.1 homepage

- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/reference/modules/installation/pages/dev.adoc
- src/reference/modules/installation/pages/index.adoc
- src/reference/modules/plugins/pages/index.adoc
https://issues.rudder.io/issues/17144
> Fixes #17144: Improve doc related to plugins/subscriptions

- src/changelogs/antora.yml
- src/reference/antora.yml
https://issues.rudder.io/issues/17210
> Fixes #17210: Rename master branch doc to 6.2

- src/reference/modules/installation/pages/_partials/upgrade_notes.adoc
- src/reference/modules/installation/pages/upgrade/debian.adoc
- src/reference/modules/installation/pages/upgrade/rhel.adoc
- src/reference/modules/installation/pages/upgrade/sles.adoc
https://issues.rudder.io/issues/17219
> Fixes #17219: Add a link to upgrade notes at the beginning of each upgrade doc page

- src/reference/modules/administration/pages/procedures.adoc
- src/reference/modules/installation/pages/_partials/agent_initial_config.adoc
- src/reference/modules/installation/pages/_partials/relay_initial_config.adoc
- src/reference/modules/usage/pages/advanced_node_management.adoc
https://issues.rudder.io/issues/17222
> Fixes #17222: Use "rudder agent policy-server" to configure policy server

- src/reference/modules/installation/pages/versions.adoc
https://issues.rudder.io/issues/17147
> Fixes #17147: Update doc for new versioning policy

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/17299
> Fixes #17299: Doc about missing uuid.hive at upgrade was not upmerged

- src/reference/modules/reference/pages/variables.adoc
https://issues.rudder.io/issues/17362
> Fixes #17362: Missing screenshot "property override visualisation"

- src/reference/modules/usage/pages/advanced_configuration_management.adoc
- src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/17369
> Fixes #17369: Typo in merge policy doc

- src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/17389
> Fixes #17389: Broken links in docs

- src/reference/modules/installation/pages/upgrade.adoc
https://issues.rudder.io/issues/17404
> Fixes #17404: Broken formatting in parent

- src/reference/dependencies/Makefile
https://issues.rudder.io/issues/17498
> Fixes #17498: Images from private plugins are not visible

- rudder-theme/src/css/custom.css
- rudder-theme/src/partials/toolbar.hbs
https://issues.rudder.io/issues/17485
> Fixes #17485: Add a banner on the docs of non-released/deprecated versions

- src/reference/modules/administration/pages/multi_server.adoc
- src/reference/modules/administration/pages/performance.adoc
- src/reference/modules/administration/pages/procedures.adoc
- src/reference/modules/administration/pages/server.adoc
https://issues.rudder.io/issues/17529
> Fixes #17529: Inconsistent commands for service management

- src/reference/modules/reference/pages/jetty_server_configuration.adoc
https://issues.rudder.io/issues/17719
> Fixes #17719: Missing documentation for overriding jetty system properties in start.ini

- rudder-theme/src/partials/navigation-explore.hbs
- rudder-theme/src/partials/toolbar.hbs
https://issues.rudder.io/issues/17648
> Fixes #17648: Prepare doc for final 6.1 release

- src/get-started/modules/ROOT/pages/configuration-policies/directive.adoc
https://issues.rudder.io/issues/17762
> Fixes #17762: Typos in directive documentation

- src/get-started/modules/ROOT/pages/configuration-policies/technique.adoc
- src/reference/modules/usage/pages/technique_editor.adoc
https://issues.rudder.io/issues/17760
> Fixes #17760: Typos in technique editor documentation

- src/reference/modules/usage/pages/technique_editor.adoc
https://issues.rudder.io/issues/17768
> Fixes #17768: Replace deprecated generic methods in technique editor documentation usage

- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/17761
> Fixes #17761: Documentation should state that SSD is recommended for more than 50 nodes

- src/reference/modules/administration/nav.list
- src/reference/modules/administration/pages/uninstall.adoc
https://issues.rudder.io/issues/17790
> Fixes #17790: Missing uninstall doc for agent

- src/get-started/modules/ROOT/pages/advanced-configuration/apply.adoc
https://issues.rudder.io/issues/17792
> Fixes #17792: Broken link in apply advanced configuration get started doc

- src/reference/modules/administration/pages/uninstall.adoc
https://issues.rudder.io/issues/17795
> Fixes #17795: Fix typos in uninstall doc

- src/reference/modules/administration/nav.list
- src/reference/modules/administration/pages/security.adoc
https://issues.rudder.io/issues/17834
> Fixes #17834: Improve documentation about communication security

- src/reference/modules/administration/pages/server.adoc
https://issues.rudder.io/issues/17880
> Fixes #17880: Add doc about network resiliency

- src/reference/modules/administration/pages/security.adoc
- src/reference/modules/administration/pages/server.adoc
https://issues.rudder.io/issues/17865
> Fixes #17865: Add docs about configuration-repository, how to sync it and what can be modified or not from outside

- src/rudder-by-example/modules/ROOT/nav.adoc
- src/rudder-by-example/modules/ROOT/pages/system/file-server-relay.adoc
https://issues.rudder.io/issues/17858
> Fixes #17858: Add a Rudder by example for using Rudder server/relays as file mirror (for repos)

- src/reference/modules/administration/pages/server.adoc
https://issues.rudder.io/issues/17892
> Fixes #17892: Typo in network resiliency documentation

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/17874
> Fixes #17874: Add support of Ubuntu 20 in doc

- src/reference/modules/administration/pages/performance.adoc
- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/17935
> Fixes #17935: Documentation is wrong about default values for data retention

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/17947
> Fixes #17947: Document how to enable/upgrade plugins after rudder upgrade

- rudder-theme/package.json
https://issues.rudder.io/issues/18056
> Fixes #18056: Fix doc build after nodejs upgrade

- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/18041
> Fixes #18041: Add DSC based node in the network flow schema in the documentation

- src/reference/modules/administration/pages/integration.adoc
https://issues.rudder.io/issues/18080
> Fixes #18080: Update links to ansible inventory plugin

- src/reference/modules/administration/pages/server.adoc
https://issues.rudder.io/issues/18104
> Fixes #18104: Move cf-serverd verbosity config into an appropriate section

- src/reference/modules/installation/pages/operating_systems.adoc
- src/reference/modules/reference/pages/contribute.adoc
https://issues.rudder.io/issues/18117
> Fixes #18117: Migrate general questions from the faq into the doc

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/17982
> Fixes #17982: The documentation should mention more obviously that upgrades from 4.3 to 6.0 are not supported

- src/reference/modules/usage/pages/advanced_configuration_management.adoc
https://issues.rudder.io/issues/17903
> Fixes #17903: Improve policy ordering doc

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/18212
> Fixes #18212: Unclear upgrade nodes about 5.0.16+

- src/reference/modules/installation/nav.adoc.src
- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/18214
> Fixes #18214: Document that JDK 15 is not supported because of nashorn removing

- src/reference/modules/reference/nav.list
https://issues.rudder.io/issues/18173
> Fixes #18173: Missing menu link to "contribute"

- rudder-theme/src/partials/header-content.hbs
- rudder-theme/yarn.lock
- src/get-started/modules/ROOT/pages/next.adoc
- src/reference/modules/administration/nav.list
- src/reference/modules/administration/pages/troubleshooting.adoc
- src/reference/modules/reference/nav.list
- src/reference/modules/reference/pages/faq.adoc
https://issues.rudder.io/issues/18190
> Fixes #18190: Add agent-server troubleshooting section

- 6.2.yml
- Makefile
- rudder-theme/src/partials/navigation-explore.hbs
- site.yml
- src/changelogs/antora.yml
- src/changelogs/dependencies/Makefile
- src/reference/antora.yml
- src/reference/dependencies/Makefile
- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/quick_agent.adoc
- src/reference/modules/installation/pages/_partials/quick_server.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/rudder-by-example/modules/ROOT/pages/system/file-server-relay.adoc
https://issues.rudder.io/issues/18368
> Fixes #18368: Prepare doc for 6.2

- site-dev.yml
https://issues.rudder.io/issues/18373
> Fixes #18373: Error when building dev site

- src/reference/modules/administration/pages/multi_server.adoc
- src/reference/modules/administration/pages/performance.adoc
- src/reference/modules/administration/pages/procedures.adoc
- src/reference/modules/administration/pages/server.adoc
- src/reference/modules/installation/pages/_partials/syslog.adoc
- src/reference/modules/installation/pages/agent/debian.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/reference/modules/installation/pages/agent/sles.adoc
- src/reference/modules/installation/pages/relay/debian.adoc
- src/reference/modules/installation/pages/relay/rhel.adoc
- src/reference/modules/installation/pages/relay/sles.adoc
- src/reference/modules/installation/pages/requirements.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/reference/modules/reference/pages/_partials/glossary/port-514.adoc
- src/reference/modules/reference/pages/architecture.adoc
- src/reference/modules/reference/pages/security.adoc
https://issues.rudder.io/issues/18142
> Fixes #18142: Remove doc related to syslog reporting

- src/reference/modules/administration/pages/uninstall.adoc
https://issues.rudder.io/issues/17803
> Fixes #17803: Advise to not desinstall rudder server if possible

- src/reference/modules/reference/pages/techniques.adoc
https://issues.rudder.io/issues/18427
> Fixes #18427: USEMETHODREPORTING in metadata documentation is missing

- src/reference/modules/plugins/pages/index.adoc
https://issues.rudder.io/issues/18454
> Fixes #18454: Add documentation about proxy in rudder package command

- rudder-theme/src/css/custom.css
https://issues.rudder.io/issues/18524
> Fixes #18524: Search window appears behind "dev version warning" bar

- rudder-theme/src/partials/navigation-explore.hbs
https://issues.rudder.io/issues/18546
> Fixes #18546: Fix links to different API versions

- src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/18467
> Fixes #18467: Correct documentation about arrray merge for node properties

- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/18532
> Fixes #18532: Improve documentation on disk space requirement

- src/reference/modules/plugins/pages/windows.adoc
https://issues.rudder.io/issues/12622
> Fixes #12622: Add a link to rudder-by-example in windows doc

- src/reference/modules/administration/pages/server.adoc
https://issues.rudder.io/issues/18702
> Fixes #18702: Wrong period for health check run in user doc

- src/reference/modules/usage/pages/configuration_management.adoc
https://issues.rudder.io/issues/18707
> Fixes #18707: Add documentation about set-force-audit in audit/enforce chapter

- rudder-theme/src/partials/navigation-explore.hbs
- rudder-theme/src/partials/toolbar.hbs
https://issues.rudder.io/issues/18756
> Fixes #18756: Mark 6.2 as final in docs

- src/rudder-by-example/modules/ROOT/nav.adoc
- src/rudder-by-example/modules/ROOT/pages/system/auto-accept-nodes.adoc
https://issues.rudder.io/issues/18780
> Fixes #18780: Rudder by example for auto-accept nodes

- src/reference/modules/installation/nav.adoc.src
- src/reference/modules/installation/pages/container.adoc
https://issues.rudder.io/issues/18794
> Fixes #18794: Document container/docker support

- src/reference/modules/plugins/pages/windows.adoc
https://issues.rudder.io/issues/18836
> Fixes #18836: Update plugin documentation

- src/reference/modules/administration/pages/integration.adoc
https://issues.rudder.io/issues/18962
> Fixes #18962: Update some plugin documentation

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/19036
> Fixes #19036: Incorrect option in pg_restore for archive 

- src/reference/modules/administration/pages/port.adoc
https://issues.rudder.io/issues/19262
> Fixes #19262: Document rudder.community.port change to rudder.policy.distribution.port.cfengine

- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/19280
> Fixes #19280: Document minimum version of JDK (8u92)

- src/reference/modules/reference/pages/build.adoc
https://issues.rudder.io/issues/19347
> Fixes #19347: Update build documentation for 7.0

- Jenkinsfile
- src/reference/dependencies/tools/ncf_doc_rudder.py
- src/reference/modules/administration/pages/server.adoc
- src/reference/modules/installation/pages/requirements.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/reference/modules/reference/pages/architecture.adoc
- src/reference/modules/reference/pages/jetty_server_configuration.adoc
- src/reference/modules/reference/pages/logs.adoc
- src/reference/modules/reference/pages/techniques.adoc
- src/reference/modules/usage/pages/advanced_configuration_management.adoc
- src/reference/modules/usage/pages/advanced_node_management.adoc
- src/rudder-by-example/modules/ROOT/pages/extending-rudder/add-new-methods.adoc
- src/rudder-by-example/modules/ROOT/pages/policies/using-secrets-in-configuration-policies.adoc
https://issues.rudder.io/issues/19360
> Fixes #19360: Add ci check for typos in docs

- src/rudder-by-example/modules/ROOT/pages/policies/reboot-provisioning.adoc
https://issues.rudder.io/issues/19361
> Fixes #19361:  Add ci check for typos in docs - master

- src/reference/modules/administration/pages/integration.adoc
https://issues.rudder.io/issues/19420
> Fixes #19420: Update Ansible integration link to Rudder inventory script

- src/reference/modules/administration/pages/server.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/19437
> Fixes #19437: Fix docs about HTTPS reporting in non-compliant mode

- src/reference/modules/usage/pages/advanced_configuration_management.adoc
https://issues.rudder.io/issues/19462
> Fixes #19462: Missing doc about methods ordering

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/19493
> Fixes #19493: Remove wrong doc about services passwords

- src/reference/modules/administration/pages/performance.adoc
https://issues.rudder.io/issues/19494
> Fixes #19494: Outdated doc for setting limit of open files for the webapp

- src/reference/modules/installation/pages/versions.adoc
https://issues.rudder.io/issues/19474
> Fixes #19474: Document more precisely versioning scheme

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/19475
> Fixes #19475: Add new rudder agent output to release notes

- src/reference/modules/administration/pages/server.adoc
https://issues.rudder.io/issues/19712
> Fixes #19712: Wrong procedure for import of configuration

- 7.0.yml
- Makefile
- rudder-theme/src/partials/navigation-explore.hbs
- site-dev.yml
- site.yml
- src/changelogs/antora.yml
- src/changelogs/dependencies/Makefile
- src/reference/antora.yml
- src/reference/dependencies/Makefile
https://issues.rudder.io/issues/19791
> Fixes #19791: Make 7.0 doc build properly

- rudder-theme/package.json
- rudder-theme/src/css/site.css
- rudder-theme/src/css/typeface-lato.css
- rudder-theme/yarn.lock
https://issues.rudder.io/issues/19796
> Fixes #19796: Add lato font to the docs

- rudder-theme/src/partials/navigation-explore.hbs
https://issues.rudder.io/issues/18992
> Fixes #18992: Add a link to rudder-lang doc in reference manual

- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/quick_agent.adoc
- src/reference/modules/installation/pages/_partials/quick_server.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
- src/reference/modules/installation/pages/_partials/upgrade_techniques.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/reference/modules/installation/pages/dev.adoc
- src/reference/modules/installation/pages/operating_systems.adoc
- src/reference/modules/installation/pages/requirements.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/reference/modules/installation/pages/versions.adoc
https://issues.rudder.io/issues/19842
> Fixes #19842: Prepare doc for 7.0

- src/reference/modules/administration/pages/multi_server.adoc
https://issues.rudder.io/issues/19849
> Fixes #19849: Update the doc for external database setup

- rudder-theme/src/css/custom.css
- rudder-theme/src/img/search.svg
https://issues.rudder.io/issues/20168
> Fixes #20168: Improve search bar visibility and appearance

- src/get-started/modules/ROOT/pages/environment/index.adoc
> Correct typo.

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/20220
> Fixes #20220: Add support for Alma and Rocky Linux

- src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/20234
> Fixes #20234: Documentation about collection access in jinja2 template is incorect

- src/rudder-by-example/modules/ROOT/nav.adoc
- src/rudder-by-example/modules/ROOT/pages/system/system-update.adoc
https://issues.rudder.io/issues/20265
> Fixes #20265: Document windows update technique

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/20125
> Fixes #20125: Update supported platform list in documentation

- src/rudder-by-example/modules/ROOT/pages/system/system-update.adoc
https://issues.rudder.io/issues/20360
> Fixes #20360: Better documentation of the windows update technique

- src/rudder-by-example/modules/ROOT/pages/system/system-update.adoc
https://issues.rudder.io/issues/20369
> Fixes #20369: Improve windows patch management technique doc

- src/reference/modules/installation/pages/_partials/debian_repo.adoc
https://issues.rudder.io/issues/20402
> Fixes #20402: 7.0 install documentation installs a 6.2 version

- src/changelogs/Makefile
https://issues.rudder.io/issues/20464
> Fixes #20464: Display images in release notes

- src/changelogs/Makefile
https://issues.rudder.io/issues/20465
> Fixes #20465: Display images in release notes - create missing dir

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/20388
> Fixes #20388: Add upgrade notes for 7.0

- src/reference/modules/installation/pages/_partials/apt_key.adoc
https://issues.rudder.io/issues/20518
> Fixes #20518: apt-key is deprecated

- src/reference/modules/usage/pages/advanced_configuration_management.adoc
- src/reference/modules/usage/pages/technique_editor.adoc
- src/rudder-by-example/modules/ROOT/nav.adoc
- src/rudder-by-example/modules/ROOT/pages/files/external-resource.adoc
https://issues.rudder.io/issues/20495
> Fixes #20495: Document how to automatically synchronize technique resources from an external repository

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/20505
> Fixes #20505: Add a note about relay upgrade order

- src/reference/modules/installation/pages/requirements.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/20507
> Fixes #20507: Add a note about recent  changes in upgrade notes

- src/reference/modules/installation/pages/_partials/debian_repo.adoc
https://issues.rudder.io/issues/20543
> Fixes #20543: Debian emits a warning if we follow the documentation way of adding the private repository

- src/reference/modules/plugins/pages/windows.adoc
https://issues.rudder.io/issues/20627
> Fixes #20627: Agent logs section is missing in doc

- rudder-theme/src/partials/navigation-explore.hbs
- rudder-theme/src/partials/toolbar.hbs
https://issues.rudder.io/issues/20626
> Fixes #20626:  Mark 7.0 as final - docs

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/20659
> Fixes #20659: Upgrade notes from 6.1|6.2 -> 7.0 title is not clear enough

- src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/20731
> Fixes #20731: Documentation about properties usage on windows node uses an incorrect syntax

- 7.1.yml
- Makefile
- site-dev.yml
- site.yml
- src/changelogs/antora.yml
- src/changelogs/dependencies/Makefile
- src/reference/antora.yml
- src/reference/dependencies/Makefile
https://issues.rudder.io/issues/20847
> Fixes #20847: Prepare 7.1 doc - borken build

- src/reference/modules/installation/nav.adoc.src
- src/reference/modules/installation/pages/agent/windows.adoc
- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/20835
> Fixes #20835: Windows support should be documented as the other agents

- src/rudder-by-example/modules/ROOT/pages/system/system-update.adoc
https://issues.rudder.io/issues/20891
> Fixes #20891: Correct doc on windows KB update

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/20888
> Fixes #20888: backup/restore doc is incomplete

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/20942
> Fixes #20942: Broken list of compatible OS in 7.0

- rudder-theme/src/partials/navigation-explore.hbs
- site.yml
- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles_repo.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/20945
> Fixes #20945: Prepare doc for 7.1

- src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/20966
> Fixes #20966: link to other option for Windows Agent CLI points to the proxy

- src/reference/modules/installation/pages/_partials/agent_initial_config.adoc
https://issues.rudder.io/issues/20982
> Fixes #20982: Document that port 5309 can be disable in node configuration

- src/reference/modules/installation/pages/_partials/agent_initial_config.adoc
- src/reference/modules/usage/pages/advanced_node_management.adoc
https://issues.rudder.io/issues/20983
> Fixes #20983: INFO should be NOTE

- src/reference/modules/administration/pages/procedures.adoc
- src/reference/modules/administration/pages/relayd.adoc
- src/reference/modules/installation/pages/_partials/relay_initial_config.adoc
- src/reference/modules/installation/pages/_partials/upgrade_techniques.adoc
- src/reference/modules/installation/pages/container.adoc
- src/reference/modules/installation/pages/index.adoc
- src/reference/modules/installation/pages/operating_systems.adoc
- src/reference/modules/installation/pages/relay/debian.adoc
- src/reference/modules/installation/pages/relay/rhel.adoc
- src/reference/modules/installation/pages/relay/sles.adoc
- src/reference/modules/installation/pages/server/debian.adoc
- src/reference/modules/installation/pages/server/rhel.adoc
- src/reference/modules/installation/pages/server/sles.adoc
- src/reference/modules/installation/pages/upgrade/debian.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/reference/modules/installation/pages/upgrade/rhel.adoc
- src/reference/modules/installation/pages/upgrade/sles.adoc
- src/reference/modules/reference/pages/architecture.adoc
https://issues.rudder.io/issues/21101
> Fixes #21101: Document new packages and installation process

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/21129
> Fixes #21129: Documentation about certificate handling during uprade is not great

- src/reference/modules/administration/pages/users.adoc
https://issues.rudder.io/issues/21249
> Fixes #21249: Case sensitive documentation

- src/reference/modules/installation/nav.adoc.src
https://issues.rudder.io/issues/21296
> Fixes #21296: Missing navigation menu for Amazon Linux 2 

- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/reference/modules/plugins/pages/index.adoc
https://issues.rudder.io/issues/21575
> Fixes #21575: Document 7.2 changes

- src/reference/modules/installation/nav.adoc.src
- src/reference/modules/installation/pages/_partials/aix_repo.adoc
- src/reference/modules/installation/pages/agent/aix.adoc
https://issues.rudder.io/issues/21604
> Fixes #21604: Mention that AIX is compatible with everything noted as "Linux"

- src/reference/modules/administration/pages/users.adoc
https://issues.rudder.io/issues/21582
> Fixes #21582: Improve user management docs

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/21676
> Fixes #21676: Document SLES15SP2 requirement

- src/reference/modules/usage/pages/advanced_configuration_management.adoc
https://issues.rudder.io/issues/21675
> Fixes #21675: User documentation of archive import/export

- src/reference/modules/installation/pages/_partials/sles12_repo.adoc
- src/reference/modules/installation/pages/_partials/sles15_repo.adoc
- src/reference/modules/installation/pages/agent/sles.adoc
- src/reference/modules/installation/pages/relay/sles.adoc
- src/reference/modules/installation/pages/server/sles.adoc
- src/reference/modules/installation/pages/upgrade/sles.adoc
https://issues.rudder.io/issues/21420
> Fixes #21420: Installation documentation for Server has a section about sles12 but we only support sles15 as of 7.0

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/21721
> Fixes #21721: Missing ubuntu 22.04 support in documentation

- rudder-theme/src/partials/navigation-explore.hbs
- rudder-theme/src/partials/toolbar.hbs
https://issues.rudder.io/issues/21879
> Fixes #21879: Remove beta header from 7.2 docs

- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/reference/modules/reference/pages/logs.adoc
https://issues.rudder.io/issues/21890
> Fixes #21890: Document the changes done to the windows agent in the 7.2 release

- rudder-theme/src/partials/footer-scripts.hbs
- rudder-theme/src/partials/head-scripts.hbs
- rudder-theme/src/partials/header-content.hbs
https://issues.rudder.io/issues/21989
> Fixes #21989: Use docsearch v3 for search integration

- src/reference/modules/installation/nav.adoc.src
- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/reference/modules/installation/pages/upgrade/postgresql.adoc
https://issues.rudder.io/issues/21979
> Fixes #21979: Postgresql upgrade guid lead to nothing

- Makefile
https://issues.rudder.io/issues/22035
> Fixes #22035: Remove 6.2 and 7.0 from doc menu - makefile

- src/reference/modules/usage/pages/advanced_node_management.adoc
https://issues.rudder.io/issues/21988
> Fixes #21988: Parent ticket doesn't tell in which version the feature was introduced

- src/reference/modules/administration/nav.list
- src/reference/modules/administration/pages/agent.adoc
https://issues.rudder.io/issues/21785
> Fixes #21785: document syslog facility configuration

- src/reference/modules/installation/pages/server/rhel7.adoc
https://issues.rudder.io/issues/22266
> Fixes #22266: Install headless jdk on AL2

- src/reference/modules/administration/pages/performance.adoc
https://issues.rudder.io/issues/22281
> Fixes #22281: Remove  checkpoint_segment from database optimsation doc

- src/get-started/modules/ROOT/pages/home.adoc
https://issues.rudder.io/issues/22286
> Fixes #22286: Broken links in docs homepage

- src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/22330
> Fixes #22330: Update windows agent installation documentation

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/22128
> Fixes #22128: Wrong Table name inside documentation

- 7.3.yml
- Makefile
- rudder-theme/src/partials/navigation-explore.hbs
- site-dev.yml
- site.yml
- src/changelogs/antora.yml
- src/changelogs/dependencies/Makefile
- src/reference/antora.yml
- src/reference/dependencies/Makefile
https://issues.rudder.io/issues/22368
> Fixes #22368: Prepare 7.3 doc

- src/reference/modules/usage/pages/web_interface.adoc
https://issues.rudder.io/issues/22367
> Fixes #22367: documentation about default login/password is invalid

- src/reference/modules/installation/pages/container.adoc
- src/reference/modules/installation/pages/quick_install.adoc
- src/reference/modules/installation/pages/requirements.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/reference/modules/reference/pages/architecture.adoc
- src/reference/modules/reference/pages/build.adoc
- src/reference/modules/reference/pages/techniques.adoc
- src/reference/modules/usage/pages/advanced_configuration_management.adoc
- src/reference/modules/usage/pages/advanced_node_management.adoc
- src/reference/modules/usage/pages/node_management.adoc
- src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/21750
Replacing previous PR: https://github.com/Normation/rudder-doc/pull/924
> Fixes #21750: versions in Rudder doc are invalid

- src/reference/modules/installation/pages/versions.adoc
https://issues.rudder.io/issues/22416
> Fixes #22416: Broken link to rudder-announce ML

- src/reference/modules/administration/pages/users.adoc
https://issues.rudder.io/issues/22429
> Fixes #22429: Add bcrypt param doc in main doc

- src/reference/modules/installation/pages/_partials/apt_key_new.adoc
- src/reference/modules/installation/pages/_partials/debian_repo_new.adoc
- src/reference/modules/installation/pages/server/debian.adoc
https://issues.rudder.io/issues/22396
> Fixes #22396: doc about configuring repositories on debian is confusing for the rudder server

- src/reference/modules/administration/pages/users.adoc
https://issues.rudder.io/issues/22382
> Fixes #22382: Update documentation for custom roles

- src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/22558
> Fixes #22558: Typo in windows install documentation

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/22583
> Fixes #22583: Typo in parent ticket

- src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/22598
> Fixes #22598: Add rudder agent verbose command in windows install 

- rudder-theme/src/partials/navigation-explore.hbs
- rudder-theme/src/partials/toolbar.hbs
- src/reference/modules/installation/nav.adoc.src
- src/reference/modules/installation/pages/_partials/aix_repo.adoc
- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/debian_repo_new.adoc
- src/reference/modules/installation/pages/_partials/msi.adoc
- src/reference/modules/installation/pages/_partials/quick_agent.adoc
- src/reference/modules/installation/pages/_partials/quick_server.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles12_repo.adoc
- src/reference/modules/installation/pages/_partials/sles15_repo.adoc
- src/reference/modules/installation/pages/agent/aix.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/reference/modules/installation/pages/agent/windows.adoc
- src/reference/modules/installation/pages/server/rhel7.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/reference/modules/installation/pages/upgrade/postgresql.adoc
- src/reference/modules/installation/pages/upgrade/windows.adoc
https://issues.rudder.io/issues/22607
> Fixes #22607: Update doc for 7.3

- src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/22613
> Fixes #22613: Document 7.3 windows specific changes

- src/reference/modules/administration/pages/security.adoc
https://issues.rudder.io/issues/22630
> Fixes #22630: Document the trust option

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/22756
> Fixes #22756: Backup/restore documentation is missing some important folder backups when using plugins

- src/reference/modules/installation/nav.adoc.src
https://issues.rudder.io/issues/22955
> Fixes #22955: Remove AL2023 from menu doc for server install

- src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/22956
> Fixes #22956: Inventory variable doc is wrong about evaluation process

- src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/23066
> Fixes #23066: Document how to script the windows agent install

- src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/23018
> Fixes #23018: Windows agent installation : Documentation improvement

- src/reference/modules/administration/pages/server.adoc
- src/reference/modules/administration/pages/webapp.adoc
- src/reference/modules/reference/pages/jetty_server_configuration.adoc
https://issues.rudder.io/issues/23026
> Fixes #23026: Add relevent items from jetty config to the webapp conf section

- src/reference/modules/installation/pages/requirements.adoc
https://issues.rudder.io/issues/23131
> Fixes #23131: correct rudder server requierment in doc

- src/reference/modules/installation/pages/_partials/al_2023_repo.adoc
- src/reference/modules/installation/pages/server/al.adoc
https://issues.rudder.io/issues/23242
> Fixes #23242: Wrong OS for amazon linux 2023 server install 

- src/reference/modules/installation/pages/server/external-db.adoc
https://issues.rudder.io/issues/23245
> Fixes #23245: doc for external db is not very clear

- rudder-theme/src/partials/navigation-explore.hbs
https://issues.rudder.io/issues/23259
> Fixes #23259: Fix version in menu for yaml tehcniques doc

- src/reference/modules/administration/pages/security.adoc
https://issues.rudder.io/issues/23333
> Fixes #23333: Update hardening guide for 8.0

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/23463
> Fixes #23463: Add an upgrade node about the removal of "move" delete mode

- rudder-theme/src/css/custom.css
https://issues.rudder.io/issues/23566
> Fixes #23566: Bold appears like normal text in the docs

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/23543
> Fixes #23543: Document the compatibility of  Windows OS classes

- src/reference/modules/installation/pages/_partials/rhel_postgres.adoc
- src/reference/modules/installation/pages/server/rhel.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
- src/reference/modules/installation/pages/upgrade/rhel.adoc
- src/reference/modules/plugins/pages/index.adoc
https://issues.rudder.io/issues/23577
> Fixes #23577: Upgrade notes for 8.0

- src/get-started/modules/ROOT/pages/home.adoc
https://issues.rudder.io/issues/23643
> Fixes #23643: Broken links in docs hmepage

- src/reference/modules/installation/pages/_partials/aix_repo.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/rudder-by-example/modules/ROOT/pages/system/update-rudder-agent-package.adoc
https://issues.rudder.io/issues/22779
> Fixes #22779: Install command with variable $releasever lead to error

- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/debian_repo_new.adoc
https://issues.rudder.io/issues/23731
> Fixes #23731: Debian source list should force architecture

- src/reference/modules/ROOT/pages/key_features.adoc
https://issues.rudder.io/issues/23917
> Fixes #23917: Fixed ref in documentation for centralized page

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/23960
> Fixes #23960: Update note for rudder-package

- Makefile
- rudder-theme/src/partials/navigation-explore.hbs
- site-dev.yml
- site.yml
- src/changelogs/antora.yml
- src/reference/antora.yml
- src/reference/dependencies/Makefile
- src/reference/modules/installation/pages/_partials/aix_repo.adoc
- src/reference/modules/installation/pages/_partials/al2023_repo.adoc
- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/debian_repo_new.adoc
- src/reference/modules/installation/pages/_partials/quick_agent.adoc
- src/reference/modules/installation/pages/_partials/quick_server.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles12_repo.adoc
- src/reference/modules/installation/pages/_partials/sles15_repo.adoc
- src/reference/modules/installation/pages/agent/aix.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/24033
> Fixes #24033: Adapt doc for 8.1

- src/reference/modules/installation/pages/_partials/aix_repo.adoc
- src/reference/modules/installation/pages/_partials/al2023_repo.adoc
- src/reference/modules/installation/pages/_partials/apt_key.adoc
- src/reference/modules/installation/pages/_partials/apt_key_new.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/rpm_key.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/rudder-by-example/modules/ROOT/pages/system/file-server-relay.adoc
- src/rudder-by-example/modules/ROOT/pages/system/update-rudder-agent-package.adoc
https://issues.rudder.io/issues/24077
> Fixes #24077: Prepare documentation for repository key change

- 8.1.yml
- src/changelogs/dependencies/Makefile
https://issues.rudder.io/issues/24136
> Fixes #24136: Broken doc build

- Makefile
https://issues.rudder.io/issues/24151
> Fixes #24151: Broken doc build

- src/reference/modules/administration/pages/server.adoc
https://issues.rudder.io/issues/24190
> Fixes #24190: layout of https://docs.rudder.io/reference/8.0/administration/server.html#_importing_configuration is broken

- src/reference/modules/usage/pages/advanced_configuration_management.adoc
https://issues.rudder.io/issues/24290
> Fixes #24290: Import/Export archive feature is no more in beta

- src/reference/modules/administration/pages/performance.adoc
https://issues.rudder.io/issues/24822
> Fixes #24822: Fix doc about XMX value

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/24901
> Fixes #24901: Specify which repo to use in compatible os page

- src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/25011
> Fixes #25011: Add doc for propagated inheritance mode from global property 

- src/reference/modules/installation/pages/agent/rhel.adoc
- src/reference/modules/installation/pages/operating_systems.adoc
- src/reference/modules/installation/pages/relay/rhel.adoc
- src/reference/modules/installation/pages/server/rhel.adoc
- src/reference/modules/installation/pages/upgrade/rhel.adoc
https://issues.rudder.io/issues/25070
> Fixes #25070: Add rocky to list of supported architecture

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/25036
> Fixes #25036: Include Ubuntu 24.04 in the list of supported OS

- src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/25262
> Fixes #25262: Adapt the variables documentation to the 8.2 syntax

- src/reference/modules/reference/pages/variables.adoc
- src/reference/modules/usage/pages/variables.adoc
https://issues.rudder.io/issues/25261
> Fixes #25261: Undocument global parameters

- 8.2.yml
- Makefile
- site.yml
- src/changelogs/antora.yml
- src/changelogs/dependencies/Makefile
https://issues.rudder.io/issues/25431
It is expected to not work completly, but we need that first step to be able to build and correct the real errors afterwards
> Fixes #25431: Adapt doc for 8.2 build

- src/reference/modules/administration/pages/security.adoc
https://issues.rudder.io/issues/25444
> Fixes #25444: User password change no longer needs restart in doc

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/25468
> Fixes #25468: Add Ubuntu 24.04 as server in documentation

- src/reference/modules/installation/pages/_partials/aix_repo.adoc
- src/reference/modules/installation/pages/_partials/al2023_repo.adoc
- src/reference/modules/installation/pages/_partials/apt_key.adoc
- src/reference/modules/installation/pages/_partials/apt_key_new.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/rpm_key.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/rudder-by-example/modules/ROOT/pages/system/file-server-relay.adoc
- src/rudder-by-example/modules/ROOT/pages/system/update-rudder-agent-package.adoc
https://issues.rudder.io/issues/25543
> Fixes #25543: Revert to using the old RPM key in the docs

- src/reference/modules/installation/pages/server/al.adoc
https://issues.rudder.io/issues/25678
> Fixes #25678: Document how to install plugins on Amazon 2023

- rudder-theme/src/partials/navigation-explore.hbs
- rudder-theme/src/partials/toolbar.hbs
https://issues.rudder.io/issues/25773
> Fixes #25773: Mark 8.2 doc as stable

- src/reference/modules/administration/pages/security.adoc
https://issues.rudder.io/issues/25623
> Fixes #25623: Missing documentation on rudder.users.cleanup.account.disableAfterLastLogin

- src/reference/modules/administration/pages/webapp.adoc
- src/reference/modules/usage/pages/variables.adoc
- src/rudder-by-example/modules/ROOT/pages/policies/reboot-provisioning.adoc
- src/rudder-by-example/modules/ROOT/pages/system/auto-accept-nodes.adoc
https://issues.rudder.io/issues/25806
> Fixes #25806: Use the system token header file in docs

- src/reference/modules/reference/pages/faq.adoc
https://issues.rudder.io/issues/25803
> Fixes #25803: Publish the audit report in the docs

- src/reference/modules/installation/pages/_partials/apt_key.adoc
https://issues.rudder.io/issues/25845
> Fixes #25845: Documented repository  Rudder public key url is incorrect

- src/reference/modules/installation/pages/_partials/apt_key.adoc
https://issues.rudder.io/issues/25850
> Fixes #25850: Parent ticket still use an incorrect url

- src/reference/modules/administration/pages/agent.adoc
- src/reference/modules/installation/pages/requirements.adoc
- src/reference/modules/reference/pages/logs.adoc
- src/reference/modules/reference/pages/reports.adoc
https://issues.rudder.io/issues/25865
> Fixes #25865: Remove references to syslog in the docs

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/25676
> Fixes #25676: Backup/Restore/Migrate documentation are missing essential bits

- src/reference/modules/installation/pages/_partials/relay_initial_config.adoc
https://issues.rudder.io/issues/25967
> Fixes #25967: Documention should advice to trigger agent run after promote a node to relay

- src/reference/modules/installation/pages/agent/rhel.adoc
https://issues.rudder.io/issues/26041
> Fixes #26041: Documentation point to the wrong repository for AL1 and 2

- src/reference/modules/installation/pages/agent/rhel.adoc
https://issues.rudder.io/issues/26129
> Fixes #26129: Typo in parent ticket upmerge

- src/reference/modules/installation/pages/agent/rhel.adoc
https://issues.rudder.io/issues/26128
> Fixes #26128: Typos in parent ticket

- src/reference/modules/installation/pages/_partials/apt_key_new.adoc
https://issues.rudder.io/issues/26143
> Fixes #26143: Doc use RPM gpg key for apt package

- rudder-theme/src/partials/navigation-explore.hbs
https://issues.rudder.io/issues/26187
> Fixes #26187: Add the 8.2 version of the techniques doc

- src/reference/modules/administration/pages/troubleshooting.adoc
https://issues.rudder.io/issues/26234
> Fixes #26234: Troubleshooting ESET software modifying certifactes by replacing issuers

- src/reference/modules/administration/pages/troubleshooting.adoc
- src/reference/modules/administration/pages/webapp.adoc
- src/reference/modules/installation/pages/upgrade/postgresql.adoc
- src/reference/modules/reference/pages/logs.adoc
- src/reference/modules/usage/pages/advanced_configuration_management.adoc
https://issues.rudder.io/issues/26312
> Fixes #26312: Change path to webapp log file in doc

- Jenkinsfile
- src/get-started/modules/ROOT/pages/advanced-configuration/rules.adoc
- src/reference/modules/administration/pages/procedures.adoc
- src/reference/modules/administration/pages/security.adoc
- src/reference/modules/installation/pages/operating_systems.adoc
- src/reference/modules/usage/pages/advanced_configuration_management.adoc
- src/reference/modules/usage/pages/advanced_node_management.adoc
- src/reference/modules/usage/pages/configuration_management.adoc
- src/reference/modules/usage/pages/variables.adoc
- src/rudder-by-example/modules/ROOT/pages/policies/using-secrets-in-configuration-policies.adoc
- typos.toml
https://issues.rudder.io/issues/26369
> Fixes #26369: Fixup rudder-doc test task

- Dockerfile
- Jenkinsfile
- ci/common.Dockerfile
https://issues.rudder.io/issues/26375
> Fixes #26375: Extern dockerfile may not always works

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/26410
> Fixes #26410: Typos in docs

- src/reference/modules/plugins/pages/index.adoc
https://issues.rudder.io/issues/26482
> Fixes #26482: Rudder package install-file command is no longer relevant in documentation

- src/get-started/modules/ROOT/pages/home.adoc
https://issues.rudder.io/issues/26601
> Fixes #26601: Fix links in docs homepage

- src/get-started/modules/ROOT/pages/home.adoc
- src/reference/dependencies/Makefile
- src/reference/modules/installation/pages/_partials/al2023_repo.adoc
- src/reference/modules/installation/pages/_partials/debian_repo.adoc
- src/reference/modules/installation/pages/_partials/debian_repo_new.adoc
- src/reference/modules/installation/pages/_partials/quick_agent.adoc
- src/reference/modules/installation/pages/_partials/quick_server.adoc
- src/reference/modules/installation/pages/_partials/rhel_postgres.adoc
- src/reference/modules/installation/pages/_partials/rhel_repo.adoc
- src/reference/modules/installation/pages/_partials/sles12_repo.adoc
- src/reference/modules/installation/pages/_partials/sles15_repo.adoc
- src/reference/modules/installation/pages/agent/rhel.adoc
- src/reference/modules/installation/pages/container.adoc
- src/reference/modules/installation/pages/server/al.adoc
- src/reference/modules/installation/pages/server/rhel.adoc
- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/26627
> Fixes #26627: Adapt doc for 8.3

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/26699
> Fixes #26699: Correct documentation about Postgresql maintenance

- src/reference/modules/usage/pages/configuration_management.adoc
https://issues.rudder.io/issues/26720
> Fixes #26720: "How score are computed" documentation

- src/reference/modules/administration/pages/procedures.adoc
https://issues.rudder.io/issues/26791
> Fixes #26791: Update ops doc for nodecompliancelevels table

- src/get-started/modules/ROOT/pages/configuration-policies/technique.adoc
- src/reference/Makefile
- src/reference/modules/usage/pages/advanced_configuration_management.adoc
- src/reference/tools/generate-nav.py
- src/rudder-by-example/modules/ROOT/pages/extending-rudder/add-new-methods.adoc
- src/rudder-by-example/modules/ROOT/pages/files/advanced-file-templating.adoc
- src/rudder-by-example/modules/ROOT/pages/files/edition-replace-line.adoc
https://issues.rudder.io/issues/26828
> Fixes #26828: Parent broke the build

- src/reference/modules/administration/pages/port.adoc
https://issues.rudder.io/issues/26875
> Fixes #26875: rudder doc doesn't explain how to change the https port on windows

- src/reference/modules/administration/pages/port.adoc
- src/reference/modules/installation/pages/agent/windows.adoc
https://issues.rudder.io/issues/26876
> Fixes #26876: Correct the windows documentation about the https port 

- rudder-theme/src/partials/header-content.hbs
https://issues.rudder.io/issues/26943
> Fixes #26943: Add link to techblog in docs

- src/reference/modules/administration/pages/users.adoc
https://issues.rudder.io/issues/27133
Goes with https://github.com/Normation/rudder-plugins/pull/859
> Fixes #27133: Some documentation references to the old user-management plugin 

- src/reference/modules/installation/pages/upgrade/notes.adoc
https://issues.rudder.io/issues/27187
> Fixes #27187: Create upgrade note details for parent ticket

- src/reference/modules/installation/pages/operating_systems.adoc
https://issues.rudder.io/issues/27362
> Fixes #27362: Add RHEL 10 in supported OS list

- src/reference/modules/reference/pages/techniques.adoc
https://issues.rudder.io/issues/27635
> Fixes #27635: Remove doc about automatically defined reporting section
